### ISSUE TITLE
Multiselection on MacOS 

### ISSUE THREAD

**Issue by hendrysadrak** [Simonwep/selection#10]
ctrl+mousedown opens context menu on MacOS.

![image](https://user-images.githubusercontent.com/4000963/39987990-e756e43c-576e-11e8-9641-b645f72dd4b4.png)

So it would be better to use cmd (⌘ keycodes 91 and 93) for multiselection on MacOS. I can PR if this is approved.

**Comment by Simonwep** [comment]
Absolutly 👍
I only don't want pull-request's regarding to #7

**Comment by Simonwep** [comment]
Oh, good! I didn't noticed ^^
