### ISSUE TITLE
How to prevent selection right after a right-click

### ISSUE THREAD

**Issue by minorbug** [Simonwep/selection#101]
I would like to prevent the selection from starting immediately following a right click (also control-click on Mac). I have a UI with contextual menus, and I do not want the selection to start after closing the menu.

I assume I would do something in `beforestart`, but I'm not surer where to begin.

**Comment by Simonwep** [comment]
[Examples?](https://github.com/Simonwep/selection/blob/master/EXAMPLES.md#preventing-the-start-of-a-selection-based-on-certain-conditions-73), if not then just return `false` in `beforestart` if you don't want the selection to, well, start.

**Comment by thiagomagro** [comment]
I think the questions is more related to the event.stopPropagation(). Is is possible to preventing the click from going through?

**Comment by getreworked** [comment]
@Simonwep An easy way to recreate this issue (On Chrome) is to right click on a selectable area and select Inspect. Not sure how you'd get around this other than to limit the click event that triggers Selection to only left mouse clicks. Perhaps another option to add to the config, e.g. `leftClickOnly: true`

**Comment by Simonwep** [comment]
Here is an [example](https://github.com/Simonwep/selection/blob/master/EXAMPLES.md#preventing-the-start-of-a-selection-based-on-certain-conditions-73) of how you could do that :)

**Comment by LouGhys** [comment]
I'm doing this:

`selectionArea.on('beforestart', beforeStartHandler)`
`  const beforeStartHandler = ({ event }: SelectionEvent) => {
    return (event as MouseEvent).buttons !== 2;
  }`

**Comment by abubelinha** [comment]
@Simonwep your example links lead me to 404 error pages

**Comment by AlbertMN** [comment]
Created a PR (#163) to add @LouGhys's example in the "[recipes](https://github.com/Simonwep/selection/blob/master/packages/vanilla/recipes.md)" file.

**Comment by Simonwep** [comment]
Closing this #163, thank you @AlbertMN!
