### ISSUE TITLE
How to keep border after selecting some components and after moseup

### ISSUE THREAD

**Issue by seelojurajesh** [Simonwep/selection#102]

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/tree/master/.github/ISSUE_TEMPLATE). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.

**Comment by seelojurajesh** [comment]
Hi Simon,

Could you please help here,
What if selection div is having max height as 500
And how to select elements by scrolling.
