### ISSUE TITLE
Text-selection breaks normal selection

### ISSUE THREAD

**Issue by kartofelek007** [Simonwep/selection#103]
#### What is the problem?

When I start second selection in middle of previous then cursor not allowed appears, and selection not start. 

#### What is the current behavior?

I select some elements. This work very well. After that I start new selection. If I start it above or below previous - this still works well. But if I start it in middle of previous selection - new selection will not start.
This was worked well in 1.7

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/wez9o7cu/).

ver 1.7
![1 7](https://user-images.githubusercontent.com/2007669/114264520-b6501d00-99eb-11eb-907c-e026bd54bb7e.gif)
As you see everything working wery well

ver 2.3
![2 3](https://user-images.githubusercontent.com/2007669/114264524-bb14d100-99eb-11eb-8c04-199e0a12e5d4.gif)
If I start new selection from middle of previus, selection will not start

In fiddle with example (https://jsfiddle.net/Simonwep/wez9o7cu/) this issue also occurs.

Code for v1.7
```js
const selection = new Selection({
    class: 'selection',
    frame: document,
    startThreshold: 10,
    disableTouch: false,
    mode: 'touch',
    tapMode: 'native',
    singleClick: true,
    selectables: [
        ".palette-element"
    ],
    startareas: ['html'],
    boundaries: ['html'],
    selectionAreaContainer: 'body',
    scrollSpeedDivider: 10,
    manualScrollSpeed: 750
})
```

Code for v2.3 (but i comment all events ant this issue still exist)
```js
const selection = new Selection({
    class: 'selection',
    startThreshold: 10,

    singleTap: {
        allow: true,
        intersect: 'touch'
    },

    allowTouch: false,
    overlap: 'invert',
    selectables: [
        ".palette-element"
    ],
    startareas: ['html'],
    boundaries: ['html'],

    scrolling: {
        speedDivider: 10,
        manualSpeed: 750
    }
})
```

#### What is the expected behavior?

work fine like version 1.7

#### Your environment:
```
Version (SelectionArea.version): 2.3
Browser: Chrome  
OS:  Windows 10
```

**Comment by Simonwep** [comment]
Caused by #99 - a simple fix for that is adding `user-select: none;` to the container. I'll add that to the docs, I don't consider this an issue _yet_. I'll take a look at it later.
