### ISSUE TITLE
Right-click when left-clicked and selection when other content selected

### ISSUE THREAD

**Issue by Baltazar5000** [Simonwep/selection#105]
#### What is the problem?
1) If you press the right mouse button while holding the left while the selection is active - SelectionJs will be not usable correctly.
2) Sometimes if you select any other content and start selecting (dragging) from it, SelectionJs will be not usable correctly.

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/wez9o7cu/).
https://jsfiddle.net/d5L6jtz9/

#### Your environment:
Version (SelectionArea.version): 2.0.3
Browser:  Chrome
OS:  Windows

**Comment by Simonwep** [comment]
See https://github.com/Simonwep/selection/blob/master/EXAMPLES.md#preventing-the-start-of-a-selection-based-on-certain-conditions-73. Just block using the right mouse button.

**Comment by Simonwep** [comment]
I'll move / merge this #106.
