### ISSUE TITLE
Shift selection improvements

### ISSUE THREAD

**Issue by Baltazar5000** [Simonwep/selection#106]
Hello. When you select range with shift first element will be unselected. This is bug or feature)? I think first element should be selected too.

> By this, the furthest point should be kept as selection-anchor, not the nearest one.

**Comment by Simonwep** [comment]
![1Smxecje54](https://user-images.githubusercontent.com/30767528/114440539-8b6fef80-9bca-11eb-8b35-fefd731a219a.gif)
That's not the case?

**Comment by Simonwep** [comment]
Well, this is actually a duplicate of #100. Who knew. This is going to be published with `v2.1.0` this weekend.
