### ISSUE TITLE
CSS zoom attribute support

### ISSUE THREAD

**Issue by marc-polizzi** [Simonwep/selection#107]
I'm using successfully selectionjs - thank for the great work - but it happens that now the div containing the items to select is possibly having a [zoom](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) attribute. This cause havoc for selectionjs.

I understand this is not a standard CSS attribute but do you think it would be possible that selectionjs somehow support this usecase? Let me know if you need more details.

Would you consider as well as a more standard way of doing a scale?

```css
transformOrigin : top left
transform : scale(factor) 
```

**Comment by Simonwep** [comment]
Hi! Partial a duplicate to #58 - Sorry, but this won't get implement. Yes - there a ways to do this but there are [just](https://stackoverflow.com/questions/44277435/css-zoom-property-not-working-with-boundingclientrectangle), [too](https://bugs.chromium.org/p/chromium/issues/detail?id=967097), [many](https://stackoverflow.com/questions/27745438/how-to-compute-getboundingclientrect-without-considering-transforms), [things](https://andreiglingeanu.me/nulify-transforms/) which would need to be done to add support for that, and we're not even talking about multiple levels of transformation (which would need to be covered for such a feature to be complete).

Is there a reason why you need to scale your element? Have you considered using `em` and `font-size` to scale your elements?

**Comment by marc-polizzi** [comment]
Hello. 

I'm scaling the content of a dashboard editor which is made of complex elements (e.g., charts, pivot-tables, etc...). I'm using selectionjs to select those elements. I've eventually switched our implementation from using the non standard zoom to:

```css
transformOrigin : top left
transform : scale(factor) 
```
 
I had to fix our code dealing with mouse events to take into account that transform. I understand there is no easy solution for supporting any kind of transformation out of the box ;-) 

I was wondering perhaps an intermediate support would be possible by passing a callback - or a configuration - to the SelectionArea that would adapt the mouse event and/or bounding rectangle logics and the like according to the transformation the user of SelectionArea has applied. But of course I'm not familiar with the code.

**Comment by Simonwep** [comment]
Unfortunately this configuration or intermediate solution would be kind of tailored to the 1% who would actually use this, besides being overly complex and complicated (it'll probably also come with performance issues and the like - for example nested transformations etc. This would become a full-blown geometry library haha). So I'm afraid that I can't do that, I want to keep this simple as possible and this goes beyond the scope of it :/

**Comment by marc-polizzi** [comment]
Fair enough. I'll have a look to the code to see if I can hack something for my own use case.
