### ISSUE TITLE
Single Click on group of multiple selected elements deselects all

### ISSUE THREAD

**Issue by kaimikacolin** [Simonwep/selection#108]
Hi All,

This might be a configuration issue on my part, but I'm wondering if the library supports this behavior.

Behavior 1
With SelectionJS:
1. Drag Select multiple items
2. Click on *one* of the items
3. Result: all items are deselected

Behavior 2
With any OS file system:
1. Drag Select multiple items
2. Click on *one* of the items
3. Result: the item you clicked remains selected

I've written a workaround to emulate Behavior 2 using the 'start' and 'stop' handlers but am I missing something in configuration? Thanks.

**Comment by Simonwep** [comment]
Hey :) This is actually done in https://github.com/Simonwep/selection/commit/51c8c0f7944f3ac0b3ec6a150ff63b3fb9e0f15e and will be part of `v2.1.0` which I'm going to release this weekend. I already noticed the lack of consistency between OS selection and selectionjs (see #106).

**Comment by kaimikacolin** [comment]
Thanks for the quick response, I will wait for that release!

**Comment by kaimikacolin** [comment]
Hello, just wanted to check in on that 2.1 release?  Thank you!

**Comment by Simonwep** [comment]
Sorry, it's released now :)

**Comment by kaimikacolin** [comment]
Awesome! Have you made that the default behavior, or is there a configuration change?

**Comment by Simonwep** [comment]
This is a core-adjustment and changes the default behaviour :) I think what you've describes is the way it should behave therefor I didn't make it opt-in.

**Comment by kaimikacolin** [comment]
Ah, I see your note related to 2.0.3 and that worked well. Thank you!

**Comment by Simonwep** [comment]
Yes, instead of blocking events I / we decided to let this be the developers decision :)
