### ISSUE TITLE
Modify Selection behavior (click in empty space / keep selection for clicked object)

### ISSUE THREAD

**Issue by Aerobraking** [Simonwep/selection#110]
Hello,

I'm trying to get 2 diferent behaviours to work, that are known from a file Explorer:

1. I have one or multiple objects selected. I make a single click on one of these selected objects. The selection contains now only this object, or keep it, if its only one object. (Normally, the selection is completly empty then)

2. I have one or multiple objects selected and I click somewhere inside the boundary, where no element is. The selection will be cleared. (Normally, no change happens to the selection)

I made a fiddle for it with comments about what my problems are, see "1." one "2." in the code. The code is mostly the basic example given in the doc. 

https://jsfiddle.net/h2n89vqa/3/

Cheers,
Konnie

**Comment by Simonwep** [comment]
Hi :)

Okay, the latter one seems to be the default case as the element you click is deselected as well. To your question 1. check out the [types file](https://github.com/Simonwep/selection/blob/master/src/types.ts#L16), you can simply use `event.target` to access the element that was clicked.

I'm not even sure if it's currently possible (except for your workaround) to keep the element if it's clicked without any additional, hacky code (you're normally not supposed to select anything in `beforestart`). I'll take a look at this this weekend!

**Comment by Simonwep** [comment]
Okay, your fiddle seems a bit over-the-top to me, is this what you're trying to achive?! I can think of two modes for now:

| Possible mode| Result |
| --- | --- |
| Normal. | ![wAmrDsckWJ](https://user-images.githubusercontent.com/30767528/117548002-cc74eb80-b032-11eb-8148-741ebf91c1cc.gif) |
| Keep. | ![jIuOOxRiWC](https://user-images.githubusercontent.com/30767528/117548054-165dd180-b033-11eb-805b-d59141f6690b.gif) |

I could imagine adding a `singleTapMode` as an option to how this should be handled (or a `singleTap` property to the store object to handle it yourself - I will have to take a look at which one's better). There's also a third, possible mode I can think of where everything is deselected if more than one element was selected before but I couldn't get that to work yet...

**Comment by Aerobraking** [comment]
Hey Simon,

thanks for the reply! I think I was a bit confused by myself. Regarding case 1: that's of course the default behaviour of your example (https://simonwep.github.io/selection/ ) and what you posted as the "Normal" mode, as I now realize. I think I somehow oversaw that after I changed the code in my programm and it didn't work that way anymore. Sorry about that.

Case 2 is also solved with your even.target mention. :) 

`for (const el of store.stored) {
    if(event.target != el){
        el.classList.remove('selected');
    }
 }`

This code put in the "beforestart" event clears the selection, when a click happened between the objects. Or is this any problem, that this happens in the beforestart? As you said that it's not supposed for selecting anything, is this also the case for clearing the selection?

**Comment by Simonwep** [comment]
Okay cool! Though I'd like to make this a bit easier in your case, using the `beforestart` event to selecting / deselecting children isn't really a "good" solution to me. I'll see what I can do to make both modes more accessible!

**Comment by Aerobraking** [comment]
Alright, thanks for your effort :)
