### ISSUE TITLE
z-index not applied on _clippingElement

### ISSUE THREAD

**Issue by voroshkov** [Simonwep/selection#114]
#### What is the problem?

Container element doesn't have `z-index: 1` applied, despite it's defined in code.

#### What is the current behavior?
<-- What happens in your situation -->
This leads to not visible selection area when some elements in DOM have higher z-index.

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/wez9o7cu/).

No need.  The issue is in code:
The change from `zIndex: '1'` to `zIndex: 1` occurred in commit [2b55c944ff345543a1af3de05ac0ba5d6d8b0fab](https://github.com/Simonwep/selection/commit/2b55c944ff345543a1af3de05ac0ba5d6d8b0fab#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)

Numeric zIndex leads to adding "px" unit to it in "css" lib, which prevents from applying it to DOM element style

#### What is the expected behavior?

Expect the _clippingElement to have z-index: 1 or even better: be configurable

#### Your environment:
```
Version (SelectionArea.version): 2.0.0
Browser:  Chrome v.90
OS:  Windows 10
```

**Comment by Simonwep** [comment]
Fix is available in [v2.1.1](https://github.com/Simonwep/selection/releases/tag/2.1.1) :)
