### ISSUE TITLE
Adding Exclude property for interactive element found in Selectable

### ISSUE THREAD

**Issue by maxime4000** [Simonwep/selection#118]
**Is your feature request related to a problem? Please describe.**
I use the selection in a table for selecting row, I need to add button which will popover some content in some cell of this table. When I click on the button, the onStart event is trigger and the row is selected. That cause a re-render of the table which make the popover disappear. 

**Describe the solution you'd like**
I would like to have a properties that could be set in a selection to exclude some element of this onClick behavior. So when I click in a row, the row is selected, but if I click in a button with some selector, the selection does not happen.
```js
{
  boundaries: [".body"],
  selectables: [".body > .row"],
  exclude: [".btn"]
}
```

**Describe alternatives you've considered**
I consider making hardcoded condition, but that seem inconsistent. In my case, unselected item will trigger the selection, but selected item will not trigger a selection which allow me to show the popover without triggering a re-render. Though, I would prefer if the selection would not happen at all when I click on that button.

**HTML structure**
```html
<div class="body">
  <div class="row"><div class="cell">row 1<button class="btn">No Selection</button></div></div>
  <div class="row"><div class="cell">row 2<button class="btn">No Selection</button></div></div>
  <div class="row"><div class="cell">row 3<button class="btn">No Selection</button></div></div>
  <div class="row"><div class="cell">row 4<button class="btn">No Selection</button></div></div>
</div>
```

**Comment by Simonwep** [comment]
Could you please provide a [CodeSandbox](https://codesandbox.io/) or [JSFiddle](https://jsfiddle.net/)? It'll help me to take a closer look at your case :) Besides that, I can imagine you could use the `:not()` selector - I'm using nothing else but `querySelectorAll` so theoretically it should work 🤔

**Comment by maxime4000** [comment]
Nice idea. I understand that I could use `.body > .row:not(.disable)` to not selecting rows that are disable which is good to know.

Though I guess my context is more complicated than this. The selectable content are rows of class="row". With the suggested selector: `.body > .row :not(.btn)` I get the right behavior when clicking on a button.  
## But there is a side effect
Now my selectables is `.body > .row *` so selecting any tag in a complex tree is a new selection. Lets said I have a complex SVG with 20 path element in it. The SVG is 16px by 16px which is small, but let's said that I move from 1px and touch 10 path in this svg. Now I have 10 added element in my object `store.changed`.  Every path in this svg will result in a new added selection because it's following the rule : `.row :not(.btn)`.

## Code Sample
In the app I'm working, I'm using the id attribut of row to know which item to select. With the `:not()` selector, I can now select any tag that is inside of `.row` except `.btn` due to the query.  This cause Added to include any element and I'm using added  setSelection not correct as the Id attribut is only set on row and not on every sub element of row. 
I comment the code that would use `:not()` as it crash the app. Possible solution to fix this: Going up in the parent tree to find row element, but now I have to handle that I might get 10 added element that has the same parent row... 
https://codesandbox.io/s/practical-cray-gtgn0?file=/src/App.js

## Though
I'm not fully sure how to explain that, so I made a small mockup to explain how I see it : 
![image](https://user-images.githubusercontent.com/4070713/120388936-c7395280-c2f9-11eb-960a-4ad768fc7636.png)

Maybe what I'm asking is a property that can "Disable selection if it's the only content that is selected" Or maybe those item cannot start a selection. Honestly, all I want is a way to click on a button in a selectable and not triggering the selection. 

Honestly I wasn't thinking this would become as complex as I thought. 

Feel free to ask more question if I'm not clear on some subject. :)

**Comment by Simonwep** [comment]
Hi! Thank you for the _very_ elaborate explanation of your problem, before I dive deep into it - does [this example](https://github.com/Simonwep/selection/blob/master/EXAMPLES.md#preventing-the-start-of-a-selection-based-on-certain-conditions-73) help you? In your case you'd be checking if the given element has the class `btn` or - even simpler, if the `type` equals `button`.

**Comment by maxime4000** [comment]
Yeah it does help me. Thanks and sorry for the inconvenience.

**Comment by Simonwep** [comment]
Hey :) No problem at all! In case someone else got the same question they'll be glad you already asked it ^^
Have a nice weekend!

**Comment by richarddavenport** [comment]
Haven't even tried yet, but putting this here for historical purposes: https://github.com/Simonwep/selection/blob/c977011ccfe7318748dcb3af1a3a94f04b11d293/EXAMPLES.md#preventing-the-start-of-a-selection-based-on-certain-conditions-73
