### ISSUE TITLE
How to disable range selection 

### ISSUE THREAD

**Issue by Ritz52** [Simonwep/selection#121]
I have implemented with the drag and drop. So my inner elements visible position and added in dom is different. That's why I want to disable shift + click range selection. Not getting how to do.

**Comment by Ritz52** [comment]
I have implemented with the drag and drop. So my inner elements visible position and added in dom is different. That's why I want to disable shift + click range selection. Not getting how to do.

**Comment by Ritz52** [comment]
Also do to I have implemented it with drag and drop so when I dragged element and even if released click button, when mouse drag over elements they gets selected.

**Comment by Simonwep** [comment]
This is currently not an option - but I'll make it one :)
I've started working on v3 - so I guess that's gonna be part of it (it's a bit difficult to add new features to v2 now that I've restructered the whole thing).

**Comment by Ritz52** [comment]
Thanks for your consideration, will wait for new features 👍

**Comment by Simonwep** [comment]
Available in [v3.0.0-beta.2](https://github.com/Simonwep/selection/releases/tag/v3.0.0-beta.2), this requires an upgrade to `v3` :)
