### ISSUE TITLE
v3 -  React / Preact and Vue3 svelte support

### ISSUE THREAD

**Issue by Simonwep** [Simonwep/selection#122]
A brand new version is awaiting selectionjs - or, as it's now called, viselect!

Changes:
* Package will be moved to the [@viselect](https://www.npmjs.com/org/viselect) organization.
* The current implementation (as of v2) will be moved to [@viselect/vanilla](https://www.npmjs.com/package/@viselect/vanilla).
* There will be a preact / react, vue, svelte and lit-element edition with the first v3 version available under @viselect/{preact,react,vue,lit,svelte}.

For now there will be **no** angular support. That'll come after the first v3 release and will get it's own issue (still in consideration).

**Comment by Simonwep** [comment]
I'll postpone the lit-element and svelte integration for now. It's important to me that we get v3 out there as soon as possible. For now there will be preact, react, vue and vanillajs support.

**Comment by Simonwep** [comment]
This issue is closed, I'll leave it pinned in case there are any question. It'll be closed in a few weeks.

**Comment by kimud6003** [comment]
I am interested in the library. 
Unfortunately, when I saw that Svelte is not supported in the v3 version, I thought about creating that feature myself. 
Can I participate?

**Comment by simonwep** [comment]
@kimud6003 Absolutely, that'd be really cool - open a pr as soon as you're ready :)
