### ISSUE TITLE
Selection area is not visible on position:fixed/absolute elements.

### ISSUE THREAD

**Issue by Alexloof** [Simonwep/selection#123]
I have problems showing the selection area when the element has a fixed or absolute position value. (Probably because of z-index?)

I guess a solution could be to add an optional classname to the div element that is created, so i can bump the z-index. Tweaking the z-index on the `.selection-area` class does not work, so i think it should be possible to tweak the style on the parent div that is created.

Does it make sense?

Br Alex

**Comment by Alexloof** [comment]
Here you go - https://codesandbox.io/s/bold-kare-f13jo?file=/src/App.js:0-1317

[![Edit bold-kare-f13jo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-kare-f13jo?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Alexloof** [comment]
So from what i can see, if the fixed positioned element has a z-index more than 1 it does not work. And unfortunately, in my case, the element must have a higher z-index than 1.

**Comment by Simonwep** [comment]
Okay, I see - the problem is that you only apply the `z-index` to the selection-area. But what you want to apply it to is the wrapper (clipping-element). That is currently not possible, I'll plan this for v3.1, with v3 will also come native preact/react support which you can use then :)

Unfortunately it's currently also not possible to access the clipping element (I'll make that a feature as well!). As a hacky workaround (which only works for the version you're currently using because of minification) you could manually apply a zIndex: https://codesandbox.io/s/laughing-platform-hbshc

**Comment by Simonwep** [comment]
Available in [v3.0.0-beta.2](https://github.com/Simonwep/selection/releases/tag/v3.0.0-beta.2), this requires an upgrade to `v3` :)

**Comment by Alexloof** [comment]
@Simonwep I have upgraded to latest, but does not look like it is working. I think the custom classname does not get attached to the div element.

https://codesandbox.io/s/boring-gagarin-i833v?file=/src/App.js

**Comment by Simonwep** [comment]
Huh, that is weird - well, I'll take a look at it later today and publish a new beta version if required :) Thank you for trying out the beta though!

**Comment by Alexloof** [comment]
@Simonwep No problems 👍  Sounds great!

**Comment by Simonwep** [comment]
I just published [v3.0.0-beta.6](https://github.com/Simonwep/selection/releases/tag/v3.0.0-beta.6) - should be fixed there.

**Comment by Alexloof** [comment]
@Simonwep Thanks now it works! 
Btw - I noticed the React wrapper broke from this update. I have written my own wrapper, but some other users might be affected.

**Comment by Simonwep** [comment]
Ah god dammit 😔 what happened? Normally the wrappers shouldn't be affected by config updates... I'll look into it later.

**Comment by Alexloof** [comment]
@Simonwep i think the error i noticed came from the deepAssign utility function.

**Comment by Simonwep** [comment]
Ah, allright - yeah that should be fixed with the most recent version - thank you :)
