### ISSUE TITLE
Nuxt.js requires transpilation to use in v2.1.2

### ISSUE THREAD

**Issue by nwittwer** [Simonwep/selection#125]
#### What is the problem?
After upgrading from 2.0.3 to 2.1.2, I am running into an error about the `.mjs` library source file needing a loader.

#### What is the current behavior?
Usage: `import SelectionArea from '@simonwep/selection-js'`
```
ERROR in ./node_modules/@simonwep/selection-js/lib/selection.min.mjs 2:1784
Module parse failed: Unexpected token (2:1784)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
```

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/wez9o7cu/).

https://codesandbox.io/s/naughty-carson-7t83s?file=/nuxt.config.js

1. Open demo
1. Notice error
1. Enable lines 4-6 in `nuxt.config.js`, as below:
```js
{
  build: {
    transpile: ['@simonwep/selection-js'],
  }
}
```
4. Restart server or reload the CodeSandbox demo
5. The error goes away

#### What is the expected behavior?
I expected this library to work out-of-the-box as it did in 2.0.3. If not, maybe the docs should mention how transpilation/Babel may be required? Or is this more of an issue from Nuxt's side?

#### Your environment:
```
Version 2.1.2
Browser:  Chrome
OS:  Windows 10
Node v14.15.3
Nuxt v2.15.7
Package manager: Yarn
```

**Comment by Simonwep** [comment]
I'd rather say that this is a nuxt "issue". ES Modules are the way to go and "old" tools such as nuxt will have to catch up at some point (check out [vite](https://vitejs.dev/) as comparison).

I'll add this to a FAQ section though.

**Comment by Simonwep** [comment]
I'll close this for now as I will favor modern builds :) Maybe I'll think of something in v3, but for now I'll keep it that way.
