### ISSUE TITLE
Installing with npm doesn't work

### ISSUE THREAD

**Issue by liquidvisual** [Simonwep/selection#13]
This looks like an awesome library. Unfortunately I can't get npm to work - ```npm install``` results in a folder ```(@simonwep/selection-js)``` with no content, other than LICENSE, package.json and README.md

```
npm install @simonwep/selection-js --save
```

**Comment by Simonwep** [comment]
Thanks  for the issue, it seems like it was broken as I modularized the project. I fixed it ([see this commit](https://github.com/Simonwep/selection/commit/e4bc88eecc2c5b8f36f53c7fe0d6ca773e6dfe2f)).

**Comment by liquidvisual** [comment]
Hi Simon, I gave it a go but NPM is still downloading 0.0.9 - does it take a while to update?

**Comment by liquidvisual** [comment]
Yep, it's working now. Thanks for that!
