### ISSUE TITLE
Selecting SVG elements onClick

### ISSUE THREAD

**Issue by jmbds** [Simonwep/selection#130]
Hello,

I am trying to implement a very simple scenario (using Vanilla JS) where it is possible to select SVG items by clicking and clicking and dragging (simmilar to the example provided in README). I managed to implement the click and drag selection but I'm having some troubles with selecting when I just click on an element. In the example, visual updates are made in the "move" event listener but in my case, even thought the event is getting caught, the store doesn't get updated and I end up with empty arrays. 
I've tested with HTML elements and it seems to work, it's something wrong with SVGs.

Am I missing some configuration or do I need to create a separate logic for clicks?

Thank you!

**Comment by Simonwep** [comment]
Could you please provide a [CodeSandbox](https://codesandbox.io/) or [JSFiddle](https://jsfiddle.net/)? It'll help me to take a closer look at your case (and much faster too) :)

**Comment by jmbds** [comment]
Absolutely, here's an example.

https://codesandbox.io/s/agitated-dewdney-v5z0x?file=/src/main.js

**Comment by Simonwep** [comment]
Okay, my bad - fixed in [v3.0.0-beta.9](https://github.com/Simonwep/selection/releases/tag/v3.0.0-beta.9) :)
