### ISSUE TITLE
Selection is empty when programmatically assigning a selection

### ISSUE THREAD

**Issue by tkoenig** [Simonwep/selection#131]
#### What is the problem?

The Selection is empty when programmatically assigning a selection using `.select`.

#### What is the current behavior?

If you assign a selection programatically (eg: `selection.select(["div:nth-child(5)"]);`) 
the events like "move" are called accordingly but `getSelection()`returns an empty array.

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

https://codesandbox.io/s/viselectvanilla-forked-3wxov?file=/src/main.ts

#### What is the expected behavior?
`getSelection()`should return the selected elements.

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...): 
Version (@viselect/<insert package>): 3.0.0.beta9
Browser:  Safari
OS:  Mac
```

**Comment by Simonwep** [comment]
Jup, that's a bug :) I'll release a new version in the upcoming days!

**Comment by Simonwep** [comment]
[v3.0.0-beta.10](https://github.com/Simonwep/selection/releases/tag/v3.0.0-beta.10) with this fix is released :)
