### ISSUE TITLE
Issues with webpack

### ISSUE THREAD

**Issue by aron-tw** [Simonwep/selection#132]
```ts
import SelectionArea from '@viselect/vanilla';
```

```
Error: ../node_modules/@viselect/vanilla/lib/viselect.esm.js 2:1945
Module parse failed: Unexpected token (2:1945)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
```

**Comment by Simonwep** [comment]
Webpack version? Environment? With webpack you'll need babel as webpack doesn't support all ES Features.

**Comment by MaxChu23** [comment]
Having the same issue right now.

### Environment:

I have a monorepo with lerna in its root.

Adding `acorn` to the root of the repo helped, but now it just interferes with other packages so I'm trying to find a solution without `acorn`.

`package.json`
```
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.4",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.14.5",
    "@storybook/addon-actions": "^6.3.4",
    "@storybook/addon-essentials": "^6.3.4",
    "@storybook/addon-links": "^6.3.4",
    "@storybook/react": "^6.3.4",
    "babel-plugin-module-resolver": "^4.1.0",
```

`.babelrc`
```
{
  "presets": ["@babel/preset-typescript", "@babel/preset-env", "@babel/preset-react"]
}

```

**Comment by Aerobraking** [comment]
I'm facing a similiar? problem. Using vue3 in electron:

`Module parse failed: Unexpected token (2:2031)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /*! @viselect/vue 3.0.0-beta.9 MIT | https://github.com/Simonwep/selection */`

`  "dependencies": {
    "@tinymce/tinymce-vue": "^4.0.4",
    "@viselect/vue": "^3.0.0-beta.9",
    "chokidar": "^3.5.2",
    "class-transformer": "^0.4.0",
    "core-js": "^3.16.0",
    "d3": "^7.0.0",
    "force-graph": "github:aerobraking/force-graph",
    "reflect-metadata": "^0.1.13",
    "tinymce": "^5.8.2",
    "underscore": "^1.13.1",
    "vue": "^3.1.5",
    "vue-panzoom": "github:Aerobraking/vue-panzoom",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@types/d3": "^6.7.5",
    "@types/electron-devtools-installer": "^2.2.0",
    "@types/underscore": "^1.11.3",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.1.5",
    "electron": "^12.0.15",
    "electron-devtools-installer": "^3.2.0",
    "sass": "^1.37.0",
    "sass-loader": "^8.0.2",
    "typescript": "^4.1.6",
    "vue-cli-plugin-electron-builder": "~2.0.0",
    "vue-loader-v16": "^16.0.0-beta.5.4",
    "worker-plugin": "^5.0.1"
  }`

**Comment by Simonwep** [comment]
What kind of webpack version are you all using? I recommend using webpack 5 as webpack 4 doesn't support (all of) ES6 out of the box. In any other case you'll have to use babel as the target for this library is ES2021 and I'm (not yet) considering providing an ES5 version. See [my comment](https://github.com/Simonwep/selection/issues/124#issuecomment-874952974) in #124 for more information.

**Comment by Aerobraking** [comment]
> 
> 
> What kind of webpack version are you all using? I recommend using webpack 5 as webpack 4 doesn't support (all of) ES6 out of the box. In any other case you'll have to use babel as the target for this library is ES2021 and I'm (not yet) considering providing an ES5 version. See [my comment](https://github.com/Simonwep/selection/issues/124#issuecomment-874952974) in #124 for more information.

I'm using version **5.51.1**. My project is set up with https://cli.vuejs.org/ and I'm far from being an expert in all these settings with webpack, babel. etc. :D Maybe I have to change some setting so it will work with typescript. At least thats sometimes the problem with some packages.

**Comment by Ghyro** [comment]
Having the same version on vanilla
```
Error: ./node_modules/@viselect/vanilla/lib/viselect.cjs.js 2:2183
Module parse failed: Unexpected token (2:2183)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
```

**Comment by gnoyixiang** [comment]
@Simonwep I don't it is right to expect everyone to upgrade to webpack 5 just to use your library. There are a lot of breaking changes that needs to be addressed when upgrading from webpack 4 to webpack 5.

**Comment by Simonwep** [comment]
I'll close this due to inactivity, please use [v2.1.2](https://github.com/Simonwep/selection/releases/tag/2.1.2) if you're using webpack-v4 you can try transpiling the dependency, use something like [vitejs](https://vitejs.dev/). See [my comment](https://github.com/Simonwep/selection/issues/124#issuecomment-874952974) in #124 for more information.

**Comment by marcofugaro** [comment]
Since it was not mentioned in this thread, people using `@viselect/react` that are stuck with the current version of create-react-app can import the es5 version like this:

```js
import SelectionArea from '@viselect/react/lib/viselect.esm.es5'
```
