### ISSUE TITLE
Drag select

### ISSUE THREAD

**Issue by lubomirblazekcz** [Simonwep/selection#135]
**Is your feature request related to a problem? Please describe.**

Curently you have to disable text selection to prevent any weird behaviour. But there are situations when selecting text is still important for the user experience.

**Describe the solution you'd like**

This could be resolved by disabling mouse drag / move selection. Leaving the user with the option to use only the mouse click selection. I didn't find any such option in the demos / readme.

**Describe alternatives you've considered**

Alternative solution could be to enable drag mouse selection only with certain keyboard key. For example holding shift and mouse drag select. 

This way I can still select text, but can disable text selection with events once shift + mouse drag is applied.

 I think both options would be great! :)

**Comment by Simonwep** [comment]
Related to #103 and #97.

I really like the Idea of the developer being able to conditionally enable / disable drag selection. I'll take a look into this :)

**Comment by lubomirblazekcz** [comment]
btw mouse selection with certain keyboard key is implemented in google drive, when you press ctrl/cmd + mouse drag, the same exact behaviour would be great :)

**Comment by Simonwep** [comment]
Would adding a `beforedrag` where you can return `false` in case you want to prevent it solve the problem? Right now I also don't see any other way to prevent dragging alone...

**Comment by lubomirblazekcz** [comment]
@Simonwep I guess that could work. Would resolve also the keyboard key, that could be simple condition in the event to return false or true 👍

**Comment by Simonwep** [comment]
Okay, I added the `beforedrag` event. It acts the same way as the `beforestart` event but for when you start making selection by dragging your mouse. I guess you could now solve the problem by checking if the `ctrl` key is pressed:

```ts
let ctrlPressed = false;
window.addEventListener('keydown', e => ctrlPressed = e.ctrlKey);
window.addEventListener('keyup', e => ctrlPressed = e.ctrlKey);

selection.on('beforedrag', () => ctrlPressed);
```

**Comment by lubomirblazekcz** [comment]
just had the time try it today and works great, thanks!
