### ISSUE TITLE
How to prevent starting selection with specific condition on Firefox and Safari browsers?

### ISSUE THREAD

**Issue by namlk-hamsa-dev** [Simonwep/selection#148]
### Discussed in https://github.com/Simonwep/selection/discussions/147

<div type='discussions-op-text'>

<sup>Originally posted by **namlk-hamsa-dev** November  9, 2021</sup>
I use @viselect/react. Since I want to prevent starting selection for cards with class 'matrix-item' I set the onBeforeStart event with the following function:

`  const handleBeforeStart = (e: any) => {
    return !e.event.path.some((item: any) => item.classList && item.classList.contains('matrix-item'));
  };`

This works fine on chrome. But when I run my code on other browsers (firefox/safari) this function doesn't work because the event.path array returned from onBeforeStart event doesn't exist.

I tried to search in the Issues list but I haven't found any ideas yet. So is there any way to solve this problem? Thanks</div>

**Comment by KKondratenya** [comment]
I think, composedPath function can solve your problem. [codesandbox](https://codesandbox.io/s/viselect-vanilla-forked-2jn08?file=/src/main.ts)

**Comment by namlk-hamsa-dev** [comment]
@KKondratenya oh it works fine. Thank you so much I've been stuck here for a few days
