### ISSUE TITLE
Auto-scrolling when moving the cursor outside of scrollable select area

### ISSUE THREAD

**Issue by vdnhi** [Simonwep/selection#150]
#### What is the problem?
I set up the vanilla selection.js and cause the problem of auto-scroll (always calling the event `move`) when the cursor is outside of the boundaries.

#### What is the current behavior?
Scrolling infinitely and trigger the `move` event listener infinitely.

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).
My code sandbox:
https://codesandbox.io/s/viselect-vanilla-forked-l299t?file=/src/main.ts

#### What is the expected behavior?
It should stop the scrolling after scrolling a range of distance from the cursor to select area boundary.

#### Your environment:
Codesandbox

#### Live demo

https://user-images.githubusercontent.com/9262617/145548285-70367315-a8b2-44bd-ba88-cce6f2252387.mov

The bug also happens on https://simonwep.github.io/selection/

https://user-images.githubusercontent.com/9262617/145548907-b36ae49f-cdde-426b-8088-cbecfc4c541e.mov

**Comment by vdnhi** [comment]
@Simonwep I think you attempted to fix this issue on this commit https://github.com/Simonwep/selection/commit/23a22945de5bb65dd4aa1b33d19146444f151bd7 but I didn't see the updated changes on the latest version `v3.0.0-beta.12`?

**Comment by Simonwep** [comment]
Closed by #151 :)
