### ISSUE TITLE
Selecting non-rectangular elements

### ISSUE THREAD

**Issue by roonie007** [simonwep/selection#156]
### Discussed in https://github.com/Simonwep/selection/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **roonie007** January 22, 2022</sup>
How can I select this SVG element only when the mouse is over the line

![image](https://user-images.githubusercontent.com/7860859/150621866-97242a9d-a048-4b52-9e53-d5881d71c7e0.png)

What is actually happening, is when ever the mouse enter the SVG RectBound element even on the transparent area the item is selected (check the picture below):

![image](https://user-images.githubusercontent.com/7860859/150621914-4b29fefe-8ba0-4b24-8fb7-8c79a4087d38.png)

What I am looking for is, how to trigger the selection only when the mouse is over the line ?
Thanks</div>

**Comment by roonie007** [comment]
@Simonwep Any help on this ?

**Comment by simonwep** [comment]
This is out-of-scope for this library, I can only suggest you to implement a fraction of this library where you can draw a shape of your choice... :/
