### ISSUE TITLE
.getSelection() returns only previously selected elements.

### ISSUE THREAD

**Issue by jmbds** [Simonwep/selection#157]
#### What is the problem?

As you described in #136, the way to get the selected and stored elements on "stop" event is calling .getSelection(). However, it doesn't seem to work when the selection is made by click and drag (selection by click works as expected).

#### What is the current behavior?
<-- What happens in your situation -->

Calling .getSelection() on "stop" event after a drag selection returns only previously selected elements.

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

https://codesandbox.io/s/viselect-svg-example-forked-99zp2?file=/src/main.js

#### What is the expected behavior?

Calling .getSelection() on "stop" event should return both selected and stored elements.

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...):  webpack
Version (@viselect/<insert package>): @viselect/3.0.0-beta.13
Browser:  Chrome / Firefox
OS:  Windows 10
```

**Comment by isepise** [comment]
Strange. If i get the selection after a delay.. its ok:
```
.on("stop", () => {
    window.setTimeout(() => {
      console.log("sel: " + selection.getSelection().length);
    }, 1000);
  });
```

**Comment by luckylooke** [comment]
It is reproducable even in official example.... where on stop event console.log returns not all selected but only selected in previous selections, without last selected group. 
![Screenshot 2022-05-06 at 06 47 56](https://user-images.githubusercontent.com/3660030/167069860-1d8ed0eb-67ff-4864-a208-78154c8d1618.png)
https://codesandbox.io/s/viselectvanilla-kt332?file=/src/main.ts
