### ISSUE TITLE
Question about Math.max variable shortcuts

### ISSUE THREAD

**Issue by liquidvisual** [Simonwep/selection#16]
Hi Simon, just a quick Q. Just out of curiosity, are there any performance gains in using the following constants outside of the ```_updateArea``` function? Or is this just a design choice?

```
const abs = Math.abs,
          max = Math.max,
          min = Math.min;
```

I'm trying to become a better programmer so it helps me to learn these things :)

**Comment by Simonwep** [comment]
Oh yeah, its only to improve the readability. If you have really long formulas or similar, you can gain some more space with them. So, for example, you save for each method, like `abs`, `max` and `min` which are very common and often used, the `Math.` part which alone are five characters.

You also save some space in the compressed version ;)

**Comment by liquidvisual** [comment]
Good to know! Thanks for that :)
