### ISSUE TITLE
Shift select is not working correctly in some cases

### ISSUE THREAD

**Issue by lubomirblazekcz** [Simonwep/selection#162]
#### What is the problem?

Two cases when this is not working properly
1. if you shift select multiple items, and then you want to select few more with shift - the whole selection shifts one item forward
2. if you shift select multiple items, and then you ctrl select one item - and shift select again, the whole selection resets

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

https://codesandbox.io/s/viselect-vanilla-forked-mq57dz?file=/src/main.ts

**Comment by Simonwep** [comment]
I cannot reproduce neither of them, is this still an issue? If so what browser / os are you using?

**Comment by lubomirblazekcz** [comment]
Sorry, this issue had to be fixed already in some version. I've posted wrong codesandbox, it was happening on the demo where there is currently beta.7 https://codesandbox.io/s/viselectvanilla-kt332?file=/src/main.ts

You should update the demos with new versions on the README.md though

**Comment by Simonwep** [comment]
Gotchy, thanks! Will do that :)
