### ISSUE TITLE
Dynamic selection box horizontal orientation is invalid

### ISSUE THREAD

**Issue by ayumni** [Simonwep/selection#164]
When the box is selected, it is valid to cancel the box selection in the vertical direction, but invalid in the horizontal direction.

**Comment by vdnhi** [comment]
@ayumni Could you please follow the Bug report template when creating a new issue?

**Comment by ayumni** [comment]
@vdnhi Regular elements are ok, irregular elements are invalid

**Comment by vdnhi** [comment]
@ayumni What are irregular elements, can I have an example code sandbox that can reproduce this issue?

**Comment by Simonwep** [comment]
As @vdnhi already said, please follow the issue template.
