### ISSUE TITLE
Separate "Select All" button/checkbox support

### ISSUE THREAD

**Issue by aleksmaksiuta** [Simonwep/selection#165]
**Problem**: User wants to use separate checkbox/button to select all items per click

**Solution**: Library provides an api to add a store/selection reference to be able to select programmatically all items via button, so I can:
1. Select all items using separate button. 
2. Inside a callback function described in p.1 programmatically select all/partial set of items

**Comment by vdnhi** [comment]
Personally, I don't think this function is the goal of this library. It is very trivial to implement your own in your application to select all the items.

**Comment by aleksmaksiuta** [comment]
> Personally, I don't think this function is the goal of this library. It is very trivial to implement your own in your application to select all the items.

Maybe I wasn't clear enough. After selecting all items via Select All button, my code adds class "selected" to selected items, but library doesn't update its internal state according the changes.
