### ISSUE TITLE
Enable/Disable option

### ISSUE THREAD

**Issue by zihniogmen** [Simonwep/selection#167]
Thanks for the library !

### Is your feature request related to a problem? Please describe.

I've implemented drag/drop features to my app and needed a way to temporarily disable selection area when drag/drop is in process. Because it can make users confused.

### **Describe the solution you'd like**
A enable/disable option (bound to SelectionOptions type) to disable selection when necessary.

**Comment by Simonwep** [comment]
Hi! Any reason why calling `.disable` directly after creating an instance isn't an option? I appreciate your PR but it seems a little redundant to be honest :/

**Comment by Simonwep** [comment]
Closed due to inactivity. Please create a new issue if you believe this is a mistake :)
