### ISSUE TITLE
Which browsers are supported

### ISSUE THREAD

**Issue by drnkwati** [Simonwep/selection#17]
Can it work in ie9?

**Comment by Simonwep** [comment]
Currently it only works in modern browsers, ie11 and below are not supported. Maybe i will add some polyfills.

**Comment by Simonwep** [comment]
Pickr also got this kind of question, and I have the same opinion regarding to selectionjs. I generally don't support IE but all more or less modern browsers like Opera, Edge, Firefox, Chrome etc. If you want to build something which should work in IE, I would suggest [Babel Polyfill](https://babeljs.io/docs/en/babel-polyfill).
