### ISSUE TITLE
Support selecting lazy loaded elements while scroll-selecting

### ISSUE THREAD

**Issue by Alexloof** [Simonwep/selection#174]
I have an infinite scroll list with pagination. Which means new elements are loaded in while you are scrolling down the list.
If I use the "select while scrolling" functionality and new elements are loaded in the meantime, those won't be picked up by the library. It works if I stop/pause the selection and activate a new one. But the behavior I am seaching for is that a user can e.g. select all elements in one go, even though they are loaded in at a later point (while you are scroll-selecting). 

Does this make sense? Tell me if I have to elaborate.

Br Alex

**Comment by Simonwep** [comment]
Hey! You can always call [`selection.resolveSelectables`](https://github.com/Simonwep/selection/tree/master/packages/vanilla#functions) to resolve newly added elements :)

**Comment by Alexloof** [comment]
Hi! Ah cool, thanks that helped @Simonwep. So now to my last issue - as my list is virtualized as well, the previously selected elements (the elements att the top if I scroll down) gets deselected while scroll-selecting. Do you have any tip on top of your mind of how that can be solved? Thanks for all help

**Comment by Alexloof** [comment]
Ok, so I solved this by manually checking if the element is still in DOM before deselecting. You can close this issue. Not sure if you wanna add this to some kind of FAQ, virtualized list is pretty common. But that is up to you. Nice work with the library 👍

**Comment by Simonwep** [comment]
Hey! Awesome that you managed to solve it by yourself so quickly, yeah I'll update the README regarding "virtual" lists or when elements get added dynamically! Have a nice weekend :)
