### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by miguelcamargo9** [Simonwep/selection#175]
We have an issue with a document that has 1300 tables, we are using your library to select some tables inside some documents, but this document is a way too big, so when we start the selection we are getting the error:

`Uncaught RangeError: Maximum call stack size exceeded`
 
 As our selectable elements are 'td', we are not sure how to attack this issue, Google Chrome just has 10402 call stack size.
 
![image](https://user-images.githubusercontent.com/12465482/190166832-1ef2c2df-b608-48c3-9102-05970ec2e7ae.png)

```const selection = new SelectionArea({
        selectionAreaClass: 'selection-area',
        selectionContainerClass: 'selection-area-container',
        container: 'body',
        document: this.$refs.document,
        selectables: ['td'],
        startareas: ['.document-viewer'],
        boundaries: ['table'],
        behaviour: {
          overlap: 'invert',
          intersect: 'touch',
          startThreshold: 10,
          scrolling: {
            speedDivider: 10,
            manualSpeed: 750,
            startScrollMargins: { x: 0, y: 0 },
          },
        },
        features: {
          touch: true,
          range: true,
          singleTap: {
            allow: true,
            intersect: 'native',
          },
        },
      });

**Comment by Simonwep** [comment]
Hey! Unfortunately your script doesn't tell me that much without the markup part... could you reproduce it on codesandbox and paste in the link?

**Comment by miguelcamargo9** [comment]
https://codesandbox.io/s/viselect-vanilla-forked-l9kn97?file=/src/main.ts

This is the link of the codesanbox, as you can see I add 130.00 of td elements, unfortunately we are working with documents that have this amount of elements (see the images above) if you change the amount to 120.00 the plugin works fine, but if it is more than that, it gets break. What do you think? Again, thanks for the answer.

![image](https://user-images.githubusercontent.com/12465482/190661856-f66b5ec4-d6a7-44e2-933a-0f6b92ba8f7a.png)

**Comment by Simonwep** [comment]
Fixed in [v3.1.1](https://github.com/Simonwep/selection/releases/tag/v3.1.1) :) Happy weekend!

**Comment by miguelcamargo9** [comment]
Thanks 🥇

**Comment by miguelcamargo9** [comment]
Sorry, do you know when the version will be released on npm?

**Comment by Simonwep** [comment]
I'm so sorry, for some reason lerna crashed during the process and the package wasn't released.  I'll fix it tonight and ping you :)

**Comment by Simonwep** [comment]
@miguelcamargo9 v3.1.1 is published :)

**Comment by miguelcamargo9** [comment]
@Simonwep  great, thank you so much.
