### ISSUE TITLE
SVG click point generated selection(or something similar)

### ISSUE THREAD

**Issue by Win546** [simonwep/selection#180]
Hi i'd like to add some sort o selection made by generating a SVG point path, more o less as the "draw on map research"  made by this website https://www.immobiliare.it/ which it's using the plugin "Leaflet(https://leafletjs.com/index.html)" to make the map interactive.

**Comment by Simonwep** [comment]
Not exactly sure what you mean - but with "SVG click point generated selection" you mean being able to draw a shape and select elements that intersect this shape instead of a rectangle?

**Comment by simonwep** [comment]
Somewhat a duplicate of #156
