### ISSUE TITLE
Selection-area broken in scrollable containers

### ISSUE THREAD

**Issue by Radius2** [Simonwep/selection#185]
Hi!
I have wrong position of selection area in scroll container
[Code](https://codesandbox.io/s/xenodochial-visvesvaraya-zjyjv7?file=/src/styles.css)

https://user-images.githubusercontent.com/25176930/203510452-9af1e60f-4701-4440-9a87-ae4a29fb81c3.mp4

**Comment by Simonwep** [comment]
What a strange bug... for some reason the area is off by the amount of margin you applied to the container. I will take a closer look at it later :)

**Comment by Simonwep** [comment]
Fixed in v3.2.1 :)
