### ISSUE TITLE
Unwanted move and stop events after beforestart event

### ISSUE THREAD

**Issue by Radius2** [Simonwep/selection#186]
From version 3.2.0 I have `move` and `stop` events between `beforestart` and `start`.
[Code](https://codesandbox.io/s/viselect-vanilla-forked-i7x9jn?file=/src/main.ts)

![image](https://user-images.githubusercontent.com/25176930/203714141-4db680a7-57dc-44fb-be04-16cff28b1cb0.png)

**Comment by Simonwep** [comment]
Seems to be caused in this line [selection/blob/master/packages/vanilla/src/index.ts#L176](https://github.com/Simonwep/selection/blob/master/packages/vanilla/src/index.ts#L176) since `false` isn't passed as second argument, I'll roll out a fix later!
