### ISSUE TITLE
onBeforeDrag prop isn't available in the React library

### ISSUE THREAD

**Issue by mattevans-dev** [Simonwep/selection#188]
#### What is the problem?

The onbeforedrag event isn't available as a prop in the react library
#### What is the current behavior?
I want to use the onbeforedrag event to disable the ability to drag in certain situations:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/55884592/209677187-424154c9-7774-45e8-8ff1-cb381b6c4ecb.png">

#### What is the expected behavior?
To have the prop available to hook in to the event.

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...):  vite
Version (@viselect/<insert package>): 3.2.2
Browser:  Chrome
OS:  Mac
```

**Comment by Simonwep** [comment]
Fixed in v3.2.3 :)

**Comment by mattevans-dev** [comment]
Fantastic, thank you for the speedy fix Simon! Just about to try it out but the new version doesn't seem to be available on npm yet

**Comment by Simonwep** [comment]
Is published :) - Took some time on my machine, I'll add a release workflow for future releases...
