### ISSUE TITLE
Viselect v3.2.3 under jsDelivr missing viselect.esm.js.map

### ISSUE THREAD

**Issue by laukstein** [Simonwep/selection#189]
Viselect v3.2.3 released under jsDelivr https://cdn.jsdelivr.net/npm/@viselect/vanilla/lib/viselect.esm.js points to `//# sourceMappingURL=viselect.esm.js.map` but is missing the file under https://cdn.jsdelivr.net/npm/@viselect/vanilla/lib/viselect.esm.js.map, returns
```
{"version":3,"file":"viselect.esm.js","sources":[],"sourcesContent":[],"names":[],"mappings":""}
```

**Comment by Simonwep** [comment]
Seems to be a bigger issue, I'll switch entirely to vite for building it for production and refactor how the project is built next weekend! Should be fixed with that :)

**Comment by Simonwep** [comment]
Fixed with changes in 411c2fc5a37adaa9a916b910e49cd2a4b96b7fe1 :)

**Comment by Simonwep** [comment]
Just a quick heads up: with v3.2.4 the location of the files for jsdelivr changed, so instead of .esm.js it's now https://cdn.jsdelivr.net/npm/@viselect/vanilla/dist/viselect.mjs and https://cdn.jsdelivr.net/npm/@viselect/vanilla/dist/viselect.mjs.map!

**Comment by Simonwep** [comment]
Ah, goddammit - I meant https://cdn.jsdelivr.net/npm/@viselect/vanilla/dist/viselect.mjs 🤦 I'll updated the README's tomorrow... This whole refactoring got me confused 😕

**Comment by laukstein** [comment]
@Simonwep what about *.esm.js file? No longer supported?

**Comment by Simonwep** [comment]
.esm.js is now .mjs (the official extension for ES6 module files)... The common-js version is still using the .js extension (e.g. universal module Format -> .umd.js)

**Comment by laukstein** [comment]
No problem. Tested and so far looks working fine.
