### ISSUE TITLE
Possibility to chose selection mode

### ISSUE THREAD

**Issue by aGautrain** [Simonwep/selection#19]
#### Feature request
**Different pre-built selection possibilities**

#### What is the current behavior?
**Default behavior :** 
If selection rectangle intersects with a pixel of one selectable element, selects it
User can provide his own selectionFilter function

#### What is the expected behavior?
Having a switch between two modes (or more ?) :
* current default behavior
* center based selection 
(if the center of the selectable element is inside the selection rectangle, selects it)

And still the possibility to provide a selectionFilter function

#### Code example
```javascript
selectionFilter(evt) {
        const rectangle = evt.selection.areaElement;
        const selectionLeft = rectangle.offsetLeft;
        const selectionTop = rectangle.offsetTop;
        const selectionWidth = rectangle.offsetWidth;
        const selectionHeight = rectangle.offsetHeight;

        const item = evt.element.getBoundingClientRect();
        const itemLeft = item.left;
        const itemTop = item.top;
        const itemWidth = item.width;
        const itemHeight = item.height;

        const itemCenterX = itemLeft + (itemWidth / 2);
        const itemCenterY = itemTop + (itemHeight / 2);

        const containsCenter = (selectionLeft < itemCenterX && itemCenterX < (selectionLeft + selectionWidth))
                                && (selectionTop < itemCenterY && itemCenterY < (selectionTop + selectionHeight));

        return containsCenter;
}
```

#### Explanation
Some might want a fast setup and this could avoid some redundant work across users
If needed I can work on a pull request :)

#### Your environment:
Not relevant (npm, 0.1.0 package)

**Comment by Simonwep** [comment]
Awesome Idea!
I've added a new option which will allow things like this. It's currently in no release so here is a snipped from the next README:
```js
// On which point an element should be selected.
// Available modes are cover (cover the entire element), center (touch the center) or
// the default mode is touch (just touching it).
mode: 'touch'
```
