### ISSUE TITLE
Expose SelectionArea instance in `@viselect/vue` package

### ISSUE THREAD

**Issue by ChuHoMan** [Simonwep/selection#191]
**Is your feature request related to a problem? Please describe.**
In dynamic lists case I want to call `selection.resolveSelectables()`. But I saw the `@viselect/vue` source code it is not exposed SelectionArea instance.

**Describe the solution you'd like**
It is the simple way to solve this problem.
```vue
//...
// make an instance reactive
const instance = shallowRef<SelectionArea | null>();
//...
defineExpose({
  instance,
});
```
this is my solution: https://codesandbox.io/s/adoring-fog-wtmft0?file=/src/components/SelectionArea.vue

**Describe alternatives you've considered**
I think call `selection.resolveSelectables()` every time when onMove Event fire is not an efficient operation.
**Additional context**
I can create a pull request if you agree with my solution.

**Comment by Simonwep** [comment]
Hey! I just looked into it, trying to solve it by watching the boundary via `MutationObserver` but I guess that would't work if you were using Teleport inside of it. So I'd gladly accept a PR if you want :) Could you maybe also export an interface called `SelectionAreaAPI` and add it as type to `defineExpose`? For those working with typescript, using refs isn't as nice in vue when it's a component and it helps the user of the SelectionArea when they "ref" the component ^^

**Comment by ChuHoMan** [comment]
> 
Okay, I can try to do it and create a PR later.
