### ISSUE TITLE
Specifying document breaks the options

### ISSUE THREAD

**Issue by Kadeluxe** [Simonwep/selection#195]
`TypeError: Cannot set property ancestorOrigins of [object Location] which has only a getter`

You shouldn't do [deepAssign](https://github.com/Simonwep/selection/blob/0b455c658a5eba6d6006d23aeab4486d4524e61f/packages/vanilla/src/index.ts#L59) on settings object like that. Your deepAssign function tries to assign defaults to the `window.document` (???) and that completely crashes the library because browsers will not allow that.
I don't know why it throws such error only for my setup and not for other users and I have no time for proper investigations but I think it was worth reporting.

**Comment by Kadeluxe** [comment]
Actually the reason why is that your test site and probably other users don't set `document` option in settings, skipping that deepAssign for that property.

**Comment by Simonwep** [comment]
I see, makes sense... Must have missed that when adding support for defining `document` :) I'll fix it this weekend or so...
