### ISSUE TITLE
Right click ?

### ISSUE THREAD

**Issue by santas156** [Simonwep/selection#20]
Is there a way to select with the right click ?

If not, there will be a good feature to do that. Working with custom contextmenu, selection with right click will work like a charm.

**Comment by Simonwep** [comment]
Awesome idea!
I've added it in 5aefcb5d03e57bcb27f37b9fa2cd3251dfb93af6 :)
Simply add this property to your configuration object:
```js
validateStart: e => e.button === 2, // MouseButton 2 is right-click
```
`e` is in this case a `MouseEvent` or `TouchEvent`. If you return `true` the selection starts, if `false` not.
Theres currently no documentation but I'll add it to the next version and with this it will appear in the README.

**Comment by CocoonCrash** [comment]
And to disable right click to be able to use it to handle a context menu ? How to we now need to configure the selection setup ?

**Comment by Simonwep** [comment]
Negate the condition?
```js
selection.on('beforestart', ({oe}) => {
    return oe.button !== 2; // oe is the original mouse-event
});
```

**Comment by CocoonCrash** [comment]
@Simonwep Thank you :)
