### ISSUE TITLE
Already selected items became deselected on page scrolling

### ISSUE THREAD

**Issue by DarknessInMe** [simonwep/selection#206]
#### What is the problem?

If you start selecting and scroll down by mouse wheel, elements on the top getting deselected

https://github.com/simonwep/selection/assets/55764867/48302cc0-5a42-400f-87bd-b0ba6bd3b3f2

#### What is the current behavior?

Already selected items became deselected

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

1. Select some items
2. Don't stop selection and scroll down
3. Stop selection and scroll back to the top
4. Observe your previously selected items

#### What is the expected behavior?

Already selected items must be kept as selected

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...): webpack ^5.76.0 (Also reproducible on demos)
Version (@viselect/vanilla). ^3.2.4. Also reproducible on latest version and on demos
Browser:  Safari 16.5
OS:  macOS Ventura 13.4
```
Also, I want to admit, that I've spent some time to figure out solution for this problem. Reason why it happens is [this line](https://github.com/simonwep/selection/blob/master/packages/vanilla/src/index.ts#L310C20-L310C20). Library expects that `wheel` event will be bubbled to the `document`. And it works fine for Chrome, but not for Safari. Seems like Safari doesn't bubble up this event by default. Simplest solution for my project was adding additional `wheel` event listener for my scrollable block. 
`scrollableBlock.addEventListener('wheel', () => {})`
In that case `wheel` event will be bubbled up to `document` and everything is ok.

**Comment by simonwep** [comment]
Thank you for looking into it! I don't have a mouse with me right now, I'll take a look at it in the upcoming week :)

**Comment by igor-sysoev** [comment]
I'm experiencing the same issue on 1.7.1 version. I tried updating to latest, which has the web-kit fix, but to no avail!
