### ISSUE TITLE
[Feature] selecting transformed elements

### ISSUE THREAD

**Issue by arnaudambro** [Simonwep/selection#21]
Hi there,

Seems to be a nice library. 
However, within the demo, I added a `transform: rotate(45deg)` to the square `div`s, and it seems that the selection doesn't take that into account, it will only consider the non-transformed divs.
It would be great if it could also select transformed divs !

**Comment by Simonwep** [comment]
I'm a little bit confused, I've tried it and everything works fine - even on transformed elements... Could you create a [fiddle](https://jsfiddle.net/) or similar where I can see the problem?

**Comment by Simonwep** [comment]
I'll close it because of inactivity. Feel free to re-open it :)
