### ISSUE TITLE
TypeScript Error: Unable to Find Declaration File for @viselect/react Module in Next.js Project

### ISSUE THREAD

**Issue by Keshav-Madhav** [simonwep/selection#211]
#### What is the problem?
I'm trying to use `@viselect/react` in my Next.js project with TypeScript. However, I'm encountering an issue where TypeScript is unable to find a declaration file for the `@viselect/react` module. This is causing my build to fail.

#### What is the current behavior?
When I try to import `@viselect/react` into my project, I get the following error:

Could not find a declaration file for module ‘@viselect/react’. ‘…/node_modules/@viselect/react/dist/viselect.mjs’ implicitly has an ‘any’ type.

#### Please provide the steps to reproduce and create a CodeSandbox.
Unfortunately, I'm unable to provide a CodeSandbox link as this issue is occurring in my local development environment. However, here are the steps to reproduce:

1. Create a new Next.js project with TypeScript.
2. Install `@viselect/react` using npm or yarn.
3. Try to import `@viselect/react` into a component.

#### What is the expected behavior?
I expect to be able to import `@viselect/react` without any TypeScript errors.

#### Your environment:
Toolset: vite
Version (@viselect/react): 3.4.0 
Browser: Chrome (latest)
OS: Windows
Framework: ReactJS
Library: NextJS
Language: Typescript

**Comment by simonwep** [comment]
Fixed in #213 :)
