### ISSUE TITLE
Extend config and implementation to allow for choice of mouse-buttons that activate the selection-area

### ISSUE THREAD

**Issue by Pietrrrek** [simonwep/selection#212]
I'd like to control which buttons activate the creation of a selection area, e.g. enabling selection only through right-click such that the left-click-dragging may perform a different action such as panning across a zoomed image or dragging.

It would be ideal to be able to select which button, or combinations of buttons, activate the creation of a selection-area under `options.behavior`

I'd gladly try to add this functionality myself, if I could get assurance that the PR would eventually get accepted (after a review of course).

**Comment by simonwep** [comment]
Closed via #214 :)
