### ISSUE TITLE
Scrolling doesn't work if done via keyboard

### ISSUE THREAD

**Issue by JunilHwang** [simonwep/selection#215]
#### What is the problem?

Selection area does not expand when scrolling with keyboard

#### What is the current behavior?

selection -> scroll by keyboard

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).

https://simonwep.github.io/selection/

https://github.com/simonwep/selection/assets/18749057/3f48258b-0501-41bd-9343-8c03c526cc2e

#### What is the expected behavior?

I expect it to be the same as scrolling with a mouse.

https://github.com/simonwep/selection/assets/18749057/148b29f7-3baf-4e00-9d77-07abb82822a7

#### Your environment:
```
Toolset (e.g. webpack, vite, vue-cli...): 
Version (@viselect/vanilla: 3.4.0
Browser:  crhome
OS:  mac 14
```

**Comment by seeniOlabode** [comment]
@simonwep I've worked on this please.
