### ISSUE TITLE
Feature Request: Selecting child element of element container selects parent.

### ISSUE THREAD

**Issue by rn10950** [Simonwep/selection#22]
#### Feature request:

Selecting a child element of a specified parent class, parent will be selected. Ex:
```  
<div>
          <img>
          <label>
    </div>
```
(clicking \<img\> or \<label\> should by-option be able to select \<div\>, and not select the children)

#### What is the current behavior?

Clicking on an element will only select itself.

(I have set selectables to the class of the \<div\> elements, still clicking on \<img\> or \<label\> still selects them.

#### Your environment:
```
Selection-version: latest
Browser-version:  Pale Moon 28 (Firefox 52-based)
Operating-system:  Windows
```

**Comment by Simonwep** [comment]
Hmm, good idea. Maybe something like a `nestedSelectables` prop which gets an Array of selectors where, if a sibling is getting clicked, the root-element get's selected.
Example:

##### Selectionjs config
```js
{
	...myWonderfulConfiguration,
	nestedSelectables: ['.sel']
}
```

##### Some HTML
```html
<div class="sel">
	<div id="outer">
		<span id="inner">Click Me!</span>	
	</div>
</div>
```

Now if the user clicks on `#outer` or `#inner` `.sel` gets selected?
Something like this?

**Comment by Simonwep** [comment]
@rn10950 I'm currently a little bit confused, option `selectables` act's exactly how you asked. If you click any child the parent gets selected. Or did I misunderstood you?

**Comment by rn10950** [comment]
@Simonwep Then maybe it is not working right for me? I have recorded a video of it, I set the container div to have a selectables class, while the img and label ones do not. 

This setup is not a normal webpage, but I don't think that would make much of a difference. I am writing an application in XUL. The white box in the window is the "browser", selection is running on the page inside, which for the most part is written as a normal webpage and JS libraries, including jQuery, work fine. This is all being rendered in Pale Moon (latest version, based on Firefox 52ESR) OS is Win2K3 with a custom win98 theme.

https://streamable.com/zvery

**Comment by Simonwep** [comment]
@rn10950 That's by far the most interesting setup I've ever seen! But It's strange, mostly because only elements which get query-selected (like `selectable`) can actually be selected. There is no way that a child also / or gets selected. The part where a single-click is getting resolved is:

```js
 // Traverse dom upwards to check if target is selectable
while (!that._selectables.includes(target)) {
	if (target.parentElement) {
		target = target.parentElement;
	} else {
		return;
	}
}
```

where `_selectables` is a resolved list of DOMElements (which you defined in `selectables`) and target is the target of a `MouseEvent`. At least the `parentElement` of the `HTML` tags are `null`, so it should be no problem IMO.

I've tried to reproduce it in Pale-Moon, without success. Is there a way to reproduce it in a [JSFiddle](https://jsfiddle.net) or similar?

**Comment by rn10950** [comment]
It replicates perfectly in JSFiddle: https://jsfiddle.net/rn10950/xpvt214o/937978/

This is going to be part of an application I am developing: a free open-source file manager written in XUL (Firefox's UI framework). Will support add-ons and themes, along with an eventual taskbar/start menu/desktop (w/ widgets).

**Comment by Simonwep** [comment]
Perfect! Okay, sorry but now I see the issue (should've seen it earlier).
You've also the option
```js
const config  = {
	...otherStuff
	containers: ['#filePane-container'],
}
```
And as written in the docs: _Query selectors from elements from which the siblings can be selected_. 
Everything, that includes **all** siblings, so just remove this line :) 
Updated Fiddle: https://jsfiddle.net/xpvt214o/938003/

**Comment by Simonwep** [comment]
But that sounds awesome! Did you put it on GitHub? :D
