### ISSUE TITLE
Vue3: Cannot resolve symbol `SelectionAreaInstance` 

### ISSUE THREAD

**Issue by lanyeeee** [simonwep/selection#232]
#### What is the problem?

I want to get the current `SelectionArea`-instance in Vue3.
My code is exactly the same as the sample code:
```vue
<template>
  <SelectionArea 
    class="container"
    :options="{selectables: '.selectable'}"
    ref="selectionAreaRef"
  >
    <div 
        v-for="id of 42"
        class="selectable"
        :key="id" 
        :data-key="id"
        :class="{selected: selected.has(id)}"
    />
  </SelectionArea>
</template>

<script lang="ts" setup>
import type {SelectionAreaInstance} from '@viselect/vue';
import {ref, reactive, onMounted} from 'vue';

const selected = reactive<Set<number>>(new Set());
const selectionAreaRef = ref<SelectionAreaInstance>()

onMounted(() => {
    // log current selection
    console.log(selectionAreaRef.value?.selection)
})
</script>
```

#### What is the current behavior?

Cannot resolve symbol `SelectionAreaInstance` 
![image](https://github.com/user-attachments/assets/d55a1313-42c0-4051-a140-0e439db42285)

#### What is the expected behavior?

Successfully imported type `SelectionAreaInstance` without error

#### Your environment:
```
Toolset (vite@5.4.1 vue@3.4.38): 
Version (@viselect/vanilla": "^3.5.1):
Browser: Chrome 127.0.6533.120
OS:  Windows11
```

**Comment by simonwep** [comment]
My bad, the correct way would be to use `const selectionAreaRef = ref<InstanceType<typeof SelectionArea>>();`
