### ISSUE TITLE
How to test integration with this package? it seems Jest and jsom don't implement `DOMRect`

### ISSUE THREAD

**Issue by carlos-algms** [simonwep/selection#236]
#### What is the problem?

The features seem to be working normally in a real Browser, but they can't be tested because Jest and JsDom don't implement the `DOMRect` class.

#### What is the current behavior?

Jest fails immediately because `DOMRect` isn't implemented.

#### What is the expected behavior?

it should be possible to test this package using Jest and JsDom.

**Comment by carlos-algms** [comment]
That was fast 😐 
Thank you very much for the fix, I really appreciate 🙇🏻.

**Comment by simonwep** [comment]
You're welcome! I'll see that I can release a new version the coming days :)
