### ISSUE TITLE
[Feature] horizontal scroll

### ISSUE THREAD

**Issue by temka1234** [Simonwep/selection#24]
Hi! Is there any plan to add horizontal scroll functionality?

P.s. Thanks for awesome library!

**Comment by Simonwep** [comment]
Haha, thanks! Hoped nobody would ask for this 😄 
I'll add it :)

**Comment by MDSilviu** [comment]
+1 this would be a good feature

**Comment by Simonwep** [comment]
Done! :) Added & improved as from 4291726e72230f601f4992547fac5284aec79b9b. I'll publish a new version in the next days, by then just use the current master branch 🙂
