### ISSUE TITLE
Why push all elements and also all childNodes?

### ISSUE THREAD

**Issue by Gcaufy** [Simonwep/selection#29]
https://github.com/Simonwep/selection/blob/b64e73f8b2cfa42d8c193efd6caeda094a747988/src/selection.js#L453-L461

**Comment by Simonwep** [comment]
See the docs:
```js
    // Query selectors from elements from which the siblings can be selected
    containers: [],
```

But yeah you're right, just the direct child's would make more sense. But this could be also accomplished via `selectables: ['.mycontainer > *']`. So I think I'll remove it :) It's pretty old, so well found 😄

**Comment by Simonwep** [comment]
Option dropped in 8d09ede59957d023e711ccc418ed2cc7fbfb79bf ;)
