### ISSUE TITLE
vue use error

### ISSUE THREAD

**Issue by cmideal** [Simonwep/selection#32]
#### Do you want to request a **feature** or report a **bug**? 
bug
ERROR in js/0.js from UglifyJs
Unexpected token: name (r) [js/0.js:11341,1617]

 if i use this in vue ,run webpack : npm run build
throw error

**Comment by Simonwep** [comment]
Please adhere to the [Issue template](https://github.com/Simonwep/selection/blob/master/.github/ISSUE_TEMPLATE.md).
