### ISSUE TITLE
Error's in console after scroll

### ISSUE THREAD

**Issue by bemiks** [Simonwep/selection#35]
#### Do you want to request a **feature** or report a **bug**? 
Bug
#### What is the current behavior?
Error's in console.
#### If the current behavior is a bug, please provide the steps to reproduce.
Start selection, then still holding left mouse button, scroll down.
#### What is the expected behavior?
Clear console.
![image](https://user-images.githubusercontent.com/32541513/57833621-ad804d80-77ba-11e9-83d7-6cd6ebaa523c.png)

**Comment by Simonwep** [comment]
Just saw scrolling during selection was never implemented, I'll treat this as feature :)

**Comment by mateuszbem** [comment]
Oh dear, alright. Thanks!

**Comment by Simonwep** [comment]
"Fixed" in 1bda7289d53912b17a16377a6c83d7020c6af373 :)

**Comment by bemiks** [comment]
When we can expect version update?

**Comment by Simonwep** [comment]
Sorry,  I'm currently a little bit busy... Just published 0.2.3 :)
