### ISSUE TITLE
preventDefault error

### ISSUE THREAD

**Issue by Tigger151515** [Simonwep/selection#37]
hi
I see some problems with { passive: false }

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
_manualScroll @ selection.min.js?72a4:7

I can't understend how to resolve this problems. All works right, but error in console

**Comment by Tigger151515** [comment]
sry, it was updated 21h :) i had previous vrsion

**Comment by Simonwep** [comment]
Haha glad it's working for you know :) see #35
