### ISSUE TITLE
Pre-defined selected items

### ISSUE THREAD

**Issue by jcsmorais** [Simonwep/selection#38]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
I'm trying to implement a list of selectable items, where some need to be selected by default.

As far as I can tell there's currently no way to do this (please correct me if I'm wrong).

One possibility would be to add support for an option that accepts a selector matching the items that should be selected by default.

#### If the current behavior is a bug, please provide the steps to reproduce.
1. Create a list of selectable items
2. Set some of these items as selected by default
3. Drag-to-select a region with no items
4. Drag-to-select any other items
5. Drag-to-select a region with no items

Here's an interactive example with 10 items, where first five are selected by default: https://codepen.io/jcsmorais/full/oROEvL

#### What is the actual behavior?
3. Items that were selected by default are still selected
5. Items that were selected on step 4. are now unselected

#### What is the expected behavior?
3. Items that were selected by default are now unselected
5. Items that were selected on step 4. are now unelected

#### Your environment:
```
Selection-version: 0.2.3
Browser-version:  Chrome Version 76.0.3809.2 (Official Build) canary (64-bit)
Operating-system:  macOS Sierra version 10.12.6
```

**Comment by Simonwep** [comment]
Great idea, that's currently not "possible". Selectionjs does not care about what classes the elements already have, so if you add `selected` to one of these - this will just mess up the result.

Anyway I'll think this will be a fantastic feature, will work on it!
For now you can manually modify `selection._selectedStore` which holds pre-selected elements. See [this edited codepen](https://codepen.io/anon/pen/oROKqv?editors=0011) - I've marked relevant pieces with a comment: `// ## type ##` :)

**Comment by jcsmorais** [comment]
@Simonwep thanks for your quick reply.

I think I wasn't clear enough on my description of the issue, sorry about that.

Your workaround makes it work in a way that every time you you select a region that has no selectable items it'll fall back to the pre-defined list. Which might be fine for some use cases, mine is a little different though - 'cause I only want the pre-defined list of selected items to kick in on initialization.

Maybe exposing a `selection.addSelection` and let users decide when and which selectable items should be "manually" added to the selection would solve both use cases?

Picking up on your codepen, what I'm describing above works by dropping additions on the `onStop` method, see: [here](https://codepen.io/jcsmorais/full/BeeowX)

**Comment by Simonwep** [comment]
Oh, I see... wasn't sure about that, glad only this piece needed to be removed :)
Yep, I'll work on something like `selection.addSelection`, seems pretty essential in hindsight 😄

**Comment by Simonwep** [comment]
Okay, I've updated your demo: [codepen](https://codepen.io/anon/pen/wbbzGW?editors=0010).

You can now use `selection.select([String|Element]|String|Element)` to manually select items, this will trigger `onMove` with a custom-crafted event and `null` as `originalEvent` :)

Unfortunately I cannot simply add a `defaults` option since the core concept is too complex for it :/
