### ISSUE TITLE
Selection with shift key

### ISSUE THREAD

**Issue by simb0** [Simonwep/selection#39]
#### Do you want to request a **feature** or report a **bug**? 
Feature

#### What is the current behavior?
Selection with holding shift is not possible.

#### What is the expected behavior?
Selection like in Windows-Explorer: While holding down the shift key, you can set the end of the selection with a mouse click.

**Comment by Simonwep** [comment]
Awesome idea :D

**Comment by simb0** [comment]
Yeah ;) Would make the use in any case more intuitive...

**Comment by Simonwep** [comment]
Added in b8a6a256b426d7fa57df003475aa8de6a9b0b70a :)
