### ISSUE TITLE
destroy/disable Selection in Vue

### ISSUE THREAD

**Issue by gweit** [Simonwep/selection#40]
Hi Simon,

I am using selection in a Vue PWA, and i implemented it as described here:

https://github.com/Simonwep/selection/issues/14

based on this:

https://codesandbox.io/s/rlx7w7l76p

I need to destroy/disable the Selection but it does not work as expected. Do you have any hint for me please?

**Comment by Simonwep** [comment]
_please make sure you are using the latest version of Selection.js_... You used a pretty old version where `.destroy()` don't even exits.

I've updated the version from `0.0.11` (which was pre-alpha) to `0.2.5`, checkout the updated demo: https://codesandbox.io/s/vue-template-qqiel - I've added a destroy button and changed IconGrid.vue a little bit :)
