### ISSUE TITLE
selectionAreaContainer is not working correctly?

### ISSUE THREAD

**Issue by yellow1912** [Simonwep/selection#41]
#### Do you want to request a **feature** or report a **bug**? 
This is a bug report
#### What is the current behavior?
Perhaps I mis-understand how this option should work, but I try to ensure that the drag-select behavior cannot happen outside certain element by specifying a dom node for this option
#### What is the expected behavior?
I expected that I cannot drag-select outside of the provided selectionAreaContainer dom node
#### Your environment:
```
Selection-version: latest from https://github.com/Simonwep/selection/tree/master/dist at the time this is posted
Browser-version:  Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Operating-system:  Windows 10
```

**Comment by Simonwep** [comment]
Ah, I believe you mean `boundaries` which is designed to specify the boundaries. `selectionAreaContainer` is just the `parent` of where the selection-area (which is an element) should be appended :)
If you got confused by `boundaries` vs `selectionAreaContainer` I'll update the readme since it seems like it isn't that obvious :D

**Comment by yellow1912** [comment]
Thank you. One quick request if I may: Sometimes we want to use specified dom node(s) as boundaries, is it possible to pass them in as well. I think in the code it just have to check if the values are dom nodes or strings.

**Comment by Simonwep** [comment]
I believe all selector/query related stuff get's resolved by [this function](https://github.com/Simonwep/selection/blob/master/src/utils.js#L115). So you can mix queries / dom-nodes whatever you want :)

**Comment by yellow1912** [comment]
Perfect, thank you @Simonwep. 1 quick question I would like to ask: is there a way to require lets say holding shift key to select? The reason is that when selection is on, other behaviors such as selecting a text to copy is disabled which is quite annoying.

**Comment by Simonwep** [comment]
You can use the `validateStart` event to check if the user pressed the shift key:
```js
{
    validateStart: e => e.shiftKey // Allow selection only if user presses the shift key
    ...yourAwesomeConfig
}

```

**Comment by yellow1912** [comment]
awesome, thank you so much
