### ISSUE TITLE
IE 11 : not working due to SCRIPT1006: Expected ')' . 

### ISSUE THREAD

**Issue by nitnand** [Simonwep/selection#44]
**bug**

line no: 8  `function Selection(options = {}) {` 

```
function Selection(options) {
options = options || {};
```

It may work , for above fix .
Thanks; 

#### Your environment:
```
Selection-version: CDN 
Browser-version:   IE 11
Operating-system:  Windows.
```

**Comment by Simonwep** [comment]
I won't support any IE version. See [browserslistrc](https://github.com/Simonwep/selection/blob/master/.browserslistrc). And in the bundle aren't even default-assignments. Checkout the [cdn bundle](https://cdn.jsdelivr.net/npm/@simonwep/selection-js/dist/selection.min.js) and search for `options=`. IE11 Throws
![image](https://user-images.githubusercontent.com/30767528/61306013-210aff00-a7ec-11e9-8c6f-01e791af0f78.png)
