### ISSUE TITLE
onOutBoundaries event?

### ISSUE THREAD

**Issue by crapthings** [Simonwep/selection#46]
https://streamable.com/qvvi4

when this happen(cross boundary) any possible to cancel the selection?

the container with paper class is the boundary

or maybe i can mess with onStart and onStop to check if the certain $el is equal?

**Comment by Simonwep** [comment]
Could you please provide a [JSFiddle](https://jsfiddle.net/Simonwep/coyepkas/)? It's near impossible to examine whats the problem, how's your setup etc.

**Comment by Simonwep** [comment]
I've commented on you other issue, It seems like you only want to create a area per drag-and-drop. You can implement this easily by yourself, this library is made for general selection purposes like on your file explorer etc. And not for making squares to "select" smth that way :)
