### ISSUE TITLE
no way to override selectables .

### ISSUE THREAD

**Issue by george12w1** [Simonwep/selection#54]
I tried to override selectables  in .on(start) with the idea of selecting only what divs i desire . i want to make a calendar event in plain javascript vanilla and i need to restrict selectables to select only what divs i want .
in this line of code "this.selectables=[".box-wrap > div."+inst._selected[0].classList[0]];" i tried to set the selectables to the first selected element className .

**Comment by Simonwep** [comment]
_"Follow the issue template (create a JSFiddle) so I can resolve it as fast as possible."_ - Please. I didn't wrote "Delete the issue template and copy the email"
