### ISSUE TITLE
Override selectable

### ISSUE THREAD

**Issue by george12w1** [Simonwep/selection#56]
#### Do you want to request a **feature** or report a **bug**?
feature
#### What is the current behavior?
After overriding  selectables in Selection.create the selection don't take in account that selectables was changed . 
#### What is the expected behavior?
After overriding  selectables i want the selection to see what elements to select and what elements to ignore .
#### Your environment:
```
Selection-version: Using CDN
Browser-version:  Chrome version 75.0.3770.100 (Official Build) (64-bit)
Operating-system:  MacOS Mojave 10.14.3
```

**Comment by Simonwep** [comment]
With overriding you mean mutating `_selectables`? Every property which starts with an underscore is basically a "private" property and shouldn't be changed manually. `_xy` properties should never be edited in any way, it will most of the time break your instance.

However, if you take a look at [README#methods](https://github.com/Simonwep/selection#methods), you can use the `option` and `resolveSelectables` function to update _selectables_ :)

**Comment by george12w1** [comment]
thank's you :D
