### ISSUE TITLE
selections is not correct if the target elements have `zoom` style property

### ISSUE THREAD

**Issue by iwillwen** [Simonwep/selection#58]
#### Do you want to request a **feature** or report a **bug**?
Yes, there is a bug

#### What is the current behavior?
![Xnip2019-11-18_12-41-47](https://user-images.githubusercontent.com/731424/69025147-d3eca300-0a00-11ea-9e5a-72924f99bf2a.jpg)

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/coyepkas/ ).

DEMO: https://jsfiddle.net/ns8f43wy/1/

#### Your environment:
```
Selection-version: 1.3.0
Browser-version: Google Chrome 78.0.3904.97
Operating-system: macOS 10.15
```

**Comment by Simonwep** [comment]
Thanks for the report!

Although I'd call it feature since this wasn't considered nor intended for usage in a zoomed context.

I'll take a look at it :)

**Comment by Simonwep** [comment]
This feature is [non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) as I just found out wherefore I won't add it.

Browsers will handle it differently and it also supports values which would difficult to resolve.
