### ISSUE TITLE
Cannot start selection on YouTube

### ISSUE THREAD

**Issue by alexherbo2** [Simonwep/selection#61]
### Steps

- Navigate to https://youtube.com.
- Open the console.
- Load https://cdn.jsdelivr.net/npm/@simonwep/selection-js/dist/selection.min.js.
- Paste the following:

``` javascript
const style = `
  .selection {
    background-color: rgba(0, 0, 255, 0.1);
    border-radius: 0.1em;
    border: 0.05em solid rgba(0, 0, 255, 0.2);
  }
`

const documentStyle = document.createElement('style')
documentStyle.textContent = style
document.documentElement.append(documentStyle)

const selection = Selection.create({
  class: 'selection',
  selectables: ['a']
}).on('start', () => {
  console.log('Selection started')
})
```

- Click and drag <kbd>Left Mouse</kbd> to make a multi-selection.

### Outcome

Nothing happens.

### Expected

Selection started.

**Comment by Simonwep** [comment]
Why do you want to do such a thing?
You don't know how YouTube handles elements, styles - it may even override prototype functions. You're trying to execute a script into an environment where you're now even sure how if it works _combined_.

You could at least, if you really wan to do such a thing post a full-snipped to make it easier for me to test it:
```js
(() => {
    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/@simonwep/selection-js/dist/selection.min.js';

    script.onload = () => {
        const style = `
            .selection {
              background-color: rgba(0, 0, 255, 0.1);
              border-radius: 0.1em;
              border: 0.05em solid rgba(0, 0, 255, 0.2);
            }
        `;

        const documentStyle = document.createElement('style');
        documentStyle.textContent = style;
        document.documentElement.append(documentStyle);

        console.log(Selection.create({
            class: 'selection',
            selectionAreaContainer: 'body',
            selectables: ['a']
        }).on('start', () => {
            console.log('Selection started');
        }))
    };

    document.head.appendChild(script);
})();
```

YouTube even may clear all elements during re-render. It may override styles, it may capture events and prevent further propagation, it may override prototypes as I said and so on....

**Comment by Simonwep** [comment]
For example, take a look at the docs and then at related DOM Elements on YouTube. You'll notice both the `html` and `body` elements have zero height. So you'd need to choose other elements.

**Comment by alexherbo2** [comment]
I want to use your extension to create multiple selections with [Krabby].

[Krabby]: https://krabby.netlify.com

**Comment by Simonwep** [comment]
Ok. What's the problem now exactly?

**Comment by alexherbo2** [comment]
I just answer your question why it might happen I use Selection on YouTube.
