### ISSUE TITLE
Latest version of selection-js not working in this example with vue

### ISSUE THREAD

**Issue by ETSmukesh** [Simonwep/selection#64]
https://codesandbox.io/s/vue-template-qqiel

I have copied this example in the project and I've installed latest selection-js package. but the latest selection-js (1.4.1) not working with this above provide example code.

I am using this version of vue "^2.6.10",

**Comment by Simonwep** [comment]
Selectionjs is event-based since `1.2.x`, see https://github.com/Simonwep/selection#events
