### ISSUE TITLE
Improve / refactor demo-code

### ISSUE THREAD

**Issue by Simonwep** [Simonwep/selection#7]
The demo-code isn't really good understandable or legible for inexperienced user, so I think it should be refactored or simplified. Ideas to simplify the selection-core are also welcome!

**Please _write_ suggestions here instead of opening a pull-request with hereto-related changes. Thanks!**

**Comment by AlvaroBernalG** [comment]
Hi @Simonwep,

I think and image could help to improve the legibility of what the library does. As  the old saying goes 'And image is worth a thousand words'

![kapture 2018-05-11 at 20 37 41](https://user-images.githubusercontent.com/12004383/39943715-d758a2c4-555b-11e8-9c51-b9a170a83d3a.gif)

**Comment by Simonwep** [comment]
Hey @AlvaroBernalG! That's a fantastic idea! If you want, you could create a extended gif (the one you used here is almost perfect) which includes multi-selection, and open an Pull-request. 
We could replace the section __Selection__ > _Selection.js is a simple, lightweight, and modern libra...._ with the gif (centered, but leave the demo link below).

That would be awesome!

**Comment by Simonwep** [comment]
Okay, I think the complexity it is necessary to keep the flexibility. I will close this issue.
