### ISSUE TITLE
Two finger scrolling on touch devices

### ISSUE THREAD

**Issue by JonFabritius** [Simonwep/selection#70]
#### Do you want to request a **feature** or report a **bug**?

Feature

#### What is the current behavior?

Two finger scrolling on touch devices is missing, and two finger touches  result in selection of elements. Figuring out the implementation is almost, but not quite in my grasp ;)

#### What is the expected behavior?

Two fingered scrolling on touch devices should retain the current selection and allow scrolling the content area without selecting elements; essentially just pausing the selecting logic during .move() and letting the OS native two finger scroll work as usual.

#### Your environment:
```
Selection-version: 1.5.0 (CDN)
Browser-version:  Safari (iPadOS 13)
Operating-system:  iPadOS 13
```

**Comment by Simonwep** [comment]
I've added a `trigger` method which can be used to achieve that kind of functionality, in your case it'd be:

```js
// Intercept start of selection
selection.on('beforestart', (() => {
    let timeout = null;

    return ({oe}) => {

        // Check if user already tapped inside of a selection-area.
        if (timeout !== null) {

            // A second pointer-event occured, ignore that one.
            clearTimeout(timeout);
            timeout = null;
        } else {

            // Wait 50ms in case the user uses two fingers to scroll.
            timeout = setTimeout(() => {

                // OK User used only one finger, we can safely initiate a selection and reset the timer.
                selection.trigger(oe);
                timeout = null;
            }, 50);
        }

        // Never start automatically.
        return false;
    };
})());
```
Added in a10c61fcb1a84228cdca94a3f97b82ea094cad73, I'll publish a new release in a few days :)

**Comment by Simonwep** [comment]
I've created a [examples.md](https://github.com/Simonwep/selection/blob/master/EXAMPLES.md) file were future requests like this can be demonstrated :)
