### ISSUE TITLE
startThreshold isPoint check looks like an error

### ISSUE THREAD

**Issue by NikitaIT** [Simonwep/selection#71]
https://github.com/Simonwep/selection/blob/40e1c1bde731ca34d6810e41bb416921371ddb6e/src/selection.js#L223

startThreshold.y - without type restriction

**Comment by Simonwep** [comment]
In favor of performance and size I'm not validating any kind of settings. It should be easy enough to avoid using invalid config data during development, every option is explained in the README :)

**Comment by NikitaIT** [comment]
@Simonwep since you are so chasing the size of the bundle:
https://github.com/Simonwep/selection/blob/40e1c1bde731ca34d6810e41bb416921371ddb6e/src/selection.js#L132-L133

https://github.com/Simonwep/selection/blob/40e1c1bde731ca34d6810e41bb416921371ddb6e/src/selection.js#L587-L589

**Comment by Simonwep** [comment]
@NikitaIT Haha thanks, I'll fix that later :) And I'm not _chasing the size_, it's just an important aspect and since its API is a tool for developers and not end-users I can leave out any checks as long as everything is kept simple 🤗
