### ISSUE TITLE
Input fields within the selection boundary cannot be focused on

### ISSUE THREAD

**Issue by au-re** [Simonwep/selection#72]
#### Do you want to request a **feature** or report a **bug**?

A bug

#### What is the current behavior?

When using selection-js, any input field within the selection boundary cannot be focused on.

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/coyepkas/ ).

I created a codepen (couldn't get the jsfiddle to work) to illustrate the issue: 
https://codepen.io/au_re/project/editor/ZbWWrj

#### What is the expected behavior?
Ideally you should still be able to focus input fields inside the selection boundary, or selectable elements 

#### Your environment:
```
Selection-version: 1.6.0
Browser-version:  Firefox/Chrome
Operating-system:  Windows/Linux
```

**Comment by Simonwep** [comment]
This kind of _wanted-behavior_ (let's not call it an issue) can be easily fixed via the [`beforestart` event](https://github.com/Simonwep/selection#events):
```js
selection.on('beforestart', ({oe}) => {
    return oe.target.tagName !== 'INPUT';
});
```

`beforestart` gets fired before a selection takes place, inside of the event-handler you can decide whether a selection should be initiated or not. In your case you only want the user to make a selection if the target-element (where the user clicked) is **not** a input-element.

**Comment by au-re** [comment]
Thanks! I should read the documentation more carefully next time :/ Great job by the way, this library is super useful!

**Comment by Simonwep** [comment]
You're welcome! I have to admit that the event-section in the docs isn't very extensive - I've just added a few inline-comments to the [event-examples](https://github.com/Simonwep/selection#events) to show how each event _could_ be used :)
