### ISSUE TITLE
Type-definitions

### ISSUE THREAD

**Issue by deser** [Simonwep/selection#74]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### What is the current behavior?
Need to add HTMLElement type on('move') handler for removed/added

**Comment by Simonwep** [comment]
Excuse me? I'm not even providing ts-types for this package (at least not yet officially), do you mean [this package](https://www.npmjs.com/package/@types/simonwep__selection-js)?

**Comment by deser** [comment]
Sure, but who support that package? Not you? Maybe it's time to convert to typescrtipt or have your own types?

**Comment by Simonwep** [comment]
Huh, if you're using selectionjs with ts you should have recognized type-search and how they maintain types. And don't you see that this package doesn't even contain ts-files? Neither I'm mentioning ts-support or types anywhere in the readme.

And typesearch is made for packages who are not actively supporting types, so there's no reason to publish your js-package and "polyfilling" your own project with types. 

I won't rewrite the code-base just for the sake of ts - maybe I'll add types sooner or later.

**Comment by deser** [comment]
>I won't rewrite the code-base just for the sake of ts - maybe I'll add types sooner or later, is it that what you want? Native ts-support?

yeah :)

**Comment by Simonwep** [comment]
I've added and updated the type-definitions for this package. Typings for the `move`-event were [already available](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/simonwep__selection-js/index.d.ts#L16) so you might have just used a really old version.

In case I'm wrong, could you please tell me what's missing [in here](https://github.com/Simonwep/selection/blob/master/types/selection.d.ts)?

**Comment by deser** [comment]
Firstly, thanks a lot!

I think you need to change this at the top:
```ts
type ElementList = Element | readonly Element[] | NodeList | HTMLCollection | HTMLElement | HTMLElement[];
```

**Comment by Simonwep** [comment]
Is that necessary? HTMLElement extends Element:
![image](https://user-images.githubusercontent.com/30767528/78994655-e8147680-7b40-11ea-8beb-c5d65d4b0a83.png)

So theoretically that should be sufficient right?
```ts
type ElementList = Element | Element[] | HTMLCollection;
```

**Comment by deser** [comment]
No, Element doesn't have necessary props which HTMLElement has :) Please, just add and release new version :)

**Comment by deser** [comment]
@Simonwep , so what? :)

**Comment by Simonwep** [comment]
@deser If `Element` isn't sufficient - that should be enough right? Because you said that only `HTMLElement` contains the require properties:

```js
type ElementList = NodeList  | HTMLCollection | HTMLElement | HTMLElement[];
``` 

Although `NodeList` _can_ contain nodes which again are missing some of the properties :/

**Comment by deser** [comment]
HTMLElement is ok. I think you can do the changes and publish package :)

**Comment by Simonwep** [comment]
Woah, no need to stress with publishing a new version. `v1.7.0` now includes type-definitions :)

**Comment by deser** [comment]
Many thanks :)
Seems one more issue:
![image](https://user-images.githubusercontent.com/3010698/80639405-a2c1d580-8a6a-11ea-9d5e-8faa1b7a5f9e.png)
selected\added\removed - all of them are of `ElementList` type I think. I think most probably you need to add to `Element` `| HTMLElement` everywhere...

**Comment by Simonwep** [comment]
You said
>  Element doesn't have necessary props which HTMLElement has

So I should probably replace all `Element` with `HTMLElement` right?

Moreover I won't publish a new version in the next weeks, I'll keep it in mind though. And I'll only publish, if any, one patch-version with just type fixes. I'm not the original author of them compared to pickr - so if you find more type-related issues please write them down here.
