### ISSUE TITLE
Preferred way to handle dynamically added/removed selectables

### ISSUE THREAD

**Issue by JonFabritius** [Simonwep/selection#77]
#### Do you want to request a **feature** or report a **bug**?

Feature

#### What is the current behavior?

The documentation and demos do not advice on handling dynamically added/removed selectables, though I imagine this could be done in some smart way (beyond my expertise).

The default behaviour appears to not listen for changes in the DOM, so some sort of action is required.

#### What is the expected behavior?

The documentation could contain a demo for dynamically added/removed selectables, or comment on the feasilibity of such behaviour in the scope of this tool (ie. if it's complex and beyond current scope).

#### Your environment:
```
Selection-version:
Browser-version:  
Operating-system:  
```

**Comment by Simonwep** [comment]
Each time a selection starts all possible selectables will get resolved which means that all _new_ elements will be taken into account. 
If you add elements _during_ a selection you have to call `selection.resolveSelectables()` as mentioned in the [methods section](https://github.com/Simonwep/selection#methods) :)

**Comment by IKnowYourStyle** [comment]
It seems not working perfectly with virtualized list (when you should remove some elements out of DOM as well).

So, for me selection detects new elements but removes previous ones (which is not in user view so they are not rendering). I call ```selection.resolveSelectables()``` on move event.
![elements](https://user-images.githubusercontent.com/67157226/85144975-92e99500-b254-11ea-8de4-1e069a670384.jpg)

My final selected elements are only the ones in green area but I would like to keep all elements (red area).

Any advice how to handle that?

Thanks.

**Comment by Simonwep** [comment]
@IKnowYourStyle Selectionjs does take care of a scrollable Environment, could you provide a JSFiddle with your problem?

**Comment by IKnowYourStyle** [comment]
Hello! Sorry for long answering.

Basic example:

[codepen](https://codepen.io/iknowyourstyle/pen/ZEQvOdP)

**Comment by IKnowYourStyle** [comment]
Am I doing something wrong?

**Comment by Simonwep** [comment]
I haven't had time yet to see if that's an actual bug, first you shouldn't call `resolveSelectables` on move because that has a massive impact performance wise. I'll take a look at it tomorrow / on the weekend - on a first look it seems to be a bug, we'll see.

PS: I have no idea why, but you're using react `v0.14.1` in your example... we're currently at version `v16.x.x`...

**Comment by Simonwep** [comment]
Okay, that was quick: No, elements has to be present in the dom - you could manually keep a Set of elements though but at lease in @IKnowYourStyle 's example that's not how it works. SelectionJS uses intersection-techniques to check whether an element touches the selection-area, if the element is not there it won't get selected (That behavior is actually undefined, I never tested what would happen in this case).
