### ISSUE TITLE
cannot catch scroll event

### ISSUE THREAD

**Issue by sungle3737** [Simonwep/selection#78]
selection catch scroll event only when there is horizontal divider

but if there is no horizontal divider, "move" function cannot catch event

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/selection/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.

**Comment by sungle3737** [comment]
[sandbox link](https://codesandbox.io/s/hardcore-carson-9s47x?file=/src/App.vue)

selection box does not follow page drag when mouse scolls

**Comment by Simonwep** [comment]
Give `#app` a height and set overflow to `auto`:
```css
#app {
    overflow: auto;
    height: 60vh;
}
```
it does not work on elements / boundaries which cover the entire page.
You should also set `#app` as one of the boundary elements e.g.
```js
boundaries: ['#app']
```

**Comment by sungle3737** [comment]
so sad.
i wish it can be possible to set height 100%
