### ISSUE TITLE
Awesome script

### ISSUE THREAD

**Issue by inglesuniversal** [Simonwep/selection#79]
Can the script support grid selection diagonally?

That way I could implement it on word search puzzles for an educational site we host.

Best regards

STAY SAFE! The world needs developers like you!

**Comment by Simonwep** [comment]
Heyy thanks :)
Could you elaborate the diagonal thing? You mean drawing a line and selecting all elements intersected by it?

**Comment by inglesuniversal** [comment]
Yes, thanks for your interest on my request.

There are a lot of wordsearch puzzle games that have that feature... but the look and smooth feel your interface has... they can't not come close to what you've accomplished so far.

some code can be run to draw the words inside a board or grid on the screen.

It would be amazing if your screen can dump under the hood... the values of the text elements so a range can be preset to detect when the whole word has been selected.

On which direction?

Any...  up --- down --- from left to right --- inverted words from right to left .... and diagonally (you have 4 axis if I am not mistaking)

You can google html5 word search games and it would give you more LIVE examples.


NOTE: Another use that I am thinking for your script would be to have a grid of user uploaded images on the screen... and that by selecting them on any direction... they can all be ... moved to another directory .... renamed or deleted from the server... Gosh that would be so neat!!!!


Best regards and STAY SAFE buddy!!!

**Comment by Simonwep** [comment]
I think that this can better be accomplished by a a custon script, using selectionjs as a helper - I want to keep it as "simple" as possible but this sounds like a rather full app to me :)
