### ISSUE TITLE
Microsoft Edge - 0: 'DOMRect' is not defined

### ISSUE THREAD

**Issue by juspeeh** [Simonwep/selection#80]
#### Do you want to request a **feature** or report a **bug**?
**BUG**

#### What is the current behavior?
Doesn't work on Microsoft Edge

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/40sLhjqp/ ).

The jsfiddle or website example doesn't work on Edge.

#### What is the expected behavior?
Works on Microsoft Edge

#### Your environment:
```
Selection-version: 1.70
Browser-version:  Microsoft Edge 55.18362.449, Microsoft EdgeHtml 18.18363
Operating-system:   Windows 10
```

**Comment by Simonwep** [comment]
Fixed (?) in 3b1f1132eabc448261e6d1b9c15019e93b99be5e, could you try the [latest version](https://github.com/Simonwep/selection/blob/master/dist/selection.min.js) from the master branch? I don't have access to Legacy Edge anymore.

**Comment by juspeeh** [comment]
That was it. Thank you! 👍

**Comment by Simonwep** [comment]
Your welcome :) I'll publish a patch-version later today!
