### ISSUE TITLE
How to add elements to selection?

### ISSUE THREAD

**Issue by alvise** [Simonwep/selection#83]
Is there a way to add item to a selection?
I saw the ".select" method but it does not seems to work as i think:

https://codepen.io/anklud/pen/MWKrXrb?editors=1111

**Comment by Simonwep** [comment]
First, `.select()` takes a selector (or multiple ones), not raw elements. Second it does not fire any events and only _appends_ these elements to the list. Both things are mentioned in the readme :)

* selection.select(query:`[String]|String`) - Manually appends elements to the selection, can be a / an array of queries / elements. Returns actual selected elements as array.

**Comment by albandum** [comment]
Hi @Simonwep  ! 
I'm trying to figure out how to select all elements with a click on a button, but same as @alvise , I must be doing something wrong.

I've tried to directly add the `.selected` class to my .file elements and then run `selection.select($('.file'))` or `selection.select(document.getElementsByClassName("file"))` on page load, but no luck.

Here's a test code I'm using. `selection_result` is returning a bunch of elements, but `getSelection()` is empty : 

```
  var selection_result = selection.select(".file")
  console.log('SELECTION RESULT', selection_result)
  console.log('SELECTION GET', selection.getSelection())
```

Console log : 

```
SELECTION RESULT (48) [div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file, div.file]
SELECTION GET []
```

Am I doing something wrong? 🤔 

Great work by the way, this is a beautiful library

**Comment by Simonwep** [comment]
@albandum `getSelection` returns the _stored_ items, you'll have to call `selection.keepSelection()` to move your selected files to the ones you want to keep. Actually I don't know why they don't get added to the selection directly, I'll take a look at this.

**Comment by albandum** [comment]
Thanks a lot, adding keepSelection does the job :)

**Comment by Simonwep** [comment]
The v2-beta will now automatically fire the move event on `.select`
