### ISSUE TITLE
Additional on('load') event 

### ISSUE THREAD

**Issue by markcampbell24** [Simonwep/selection#84]
Is it possible to expose a .on('load') type event or add callback to setup options

It would be useful to have a hook in order to run functions that aren't tied to interaction for example:
- Provide user feedback/prompts
- Reload a previous selection stored in a data source

apologies if I missed it

**Comment by Simonwep** [comment]
Are you talking about an event fired after [_init](https://github.com/Simonwep/selection/blob/master/src/selection.js#L60) has been called (e.g. preparing the area-element)? Or what do you expect to be finished if `load` gets fired? There's no real "setup" and normally directly after instantiation it's ready to use 🤔

**Comment by markcampbell24** [comment]
What I'm hoping for is an event that would allow the reloading of a previous selection, a selection that could have been stored in a database/returned from local storage for example. 

All of the events currently available handle the interaction directly with the select-able elements within the area-element, 
on('beforestart', 'start', 'move', 'end')

**example:**
```
on('ready', () => {  
  for(const el in previouslySelected ) { 
    inst.select(el);
    ...
  }  
})
```

**Comment by Simonwep** [comment]
You can call `.select` any time, the thing is that this will only _append_ these elements to the selection, adding classes to them is something you'd need to take care of, see #83 :/

**Comment by albandum** [comment]
Hi ! 
I'm trying to figure out how to select all elements by default on page load, and the only thing I would would be a on('load') as described here. Or am I missing a point somewhere?

Great work by the way, this is a beautiful library

**Comment by Simonwep** [comment]
Select now works as expected, an `init` event is not necessary as the selection isntance is ready upon creation :)
