### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by frommyuk** [Simonwep/selection#87]
Hi Simon,

This function is completely wonderful, thanks so much for developing it.

I am implementing it in a FileMaker 19 application, and it works really well on Mac, but FileMaker forces Internet Explorer for Windows, and something is preventing it from working on my PC. I can only assume there is a part of the code the IE doesn't like.

Is this an issue you have encountered before?

James

**Comment by NateSeymour** [comment]
Hi frommyuk,

IE is not supported by `selection`. Thank you for your interest in this library.

Nathan
