### ISSUE TITLE
Click on a startarea will prevent the default mousedown event

### ISSUE THREAD

**Issue by g7s** [Simonwep/selection#89]
#### Do you want to request a **feature** or report a **bug**?
Bug
#### What is the current behavior?
Clicking inside a `startarea` will not make a focused input loose focus
#### What is the expected behavior?
Clicking inside a `startarea` the default mousedown event should not be prevented

I believe the line that produces this faulty behavior is https://github.com/Simonwep/selection/blob/4cb3147e199d8f08bc0b8e43078893948d5f03ad/src/selection.js#L146

What was this FF scrolling thing that made you introduce this line?

**Comment by Simonwep** [comment]
This is somehow related to #72 and #65. I'll look into it :)

**Comment by g7s** [comment]
Sure yeah #72 is happening for exactly the same reason. I guess preventing the mousedown introduces more issues than it solves.

**Comment by Simonwep** [comment]
This has finally been fixed (for good hopefully)...  Check out the [fourth iteration](https://github.com/Simonwep/selection/releases/tag/2.0.0-beta.4) of `2.0.0-beta` where this fix has been released with :)
