### ISSUE TITLE
Selecting while scrolling won't stop if mouseup event is outside of area

### ISSUE THREAD

**Issue by frdmir** [Simonwep/selection#92]
#### What is the problem?
The scroll will not stop and gets locked if mouseup event happens outside of the area

This is somehow related to issue https://github.com/Simonwep/selection/issues/48

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/wez9o7cu/).

https://user-images.githubusercontent.com/23293444/103773003-2922b400-5009-11eb-9951-4331b3596ce8.mp4

It can be reproduced on demo site (https://simonwep.github.io/selection/)

#### Your environment:
```
Version (SelectionArea.version): 2.0.0-beta.5
Browser:  Vivaldi 3.5.2115.81 (Stable channel) (64 bits)
OS:  Ubuntu 20.04 LTS
```

**Comment by Simonwep** [comment]
I'll release a new beta version today or later this week, thanks for your report! Seems like regression ^^
