### ISSUE TITLE
Selection of dynamically generated elements

### ISSUE THREAD

**Issue by minorbug** [Simonwep/selection#93]
**Is your feature request related to a problem? Please describe.**
A lot of scrollable views create DOM elements only when they are visible within a view to save resources. The Selection library only seems to make elements selectable if they are in the DOM at selection start. 

**Describe the solution you'd like**
Either have the "selectables" option include selection of newly created DOM elements, such as during scroll, or provide an example of using the events. 

**Describe alternatives you've considered**
Disabling scrolling (undesirable), or force view to render all DOM elements which considerably impacts performance on large datasets (scrollable view of 1,000,000 boxes, for example

**Comment by Simonwep** [comment]
Does [resolveSelectables](https://github.com/Simonwep/selection#methods) solve your problem? It was introduced for this purpose.

**Comment by minorbug** [comment]
Yes, thank you.
