### ISSUE TITLE
Have a throttle option in the selection.

### ISSUE THREAD

**Issue by maxime4000** [Simonwep/selection#96]
**Is your feature request related to a problem? Please describe.**

I've been using SelectionJS with React-Table for handling selection on the Table component I work on. Problems is that onMove function is call too much time that React-Table need to re-render every time onMove is call, which cause performance issues. So I need to throttle onMove function to not re-render the table every time I move my mouse. But if I throttle, some added/removed selection are missed and the selection is not accurate anymore. 

**Describe the solution you'd like**

I was going to do a system to queue/combine SelectionEvent with throttle, so I can keep track of selection without spamming my table to re-render as much as it can be. But I think SelectionJS should have the throttle option instead. It should be a parameter to said, I want onMove to be called with at least X interval. This limiter would allow the selection to work with heavy render task by lowering the number of call the onMove function is called.

**Describe alternatives you've considered**

If I do the system outside of SelectionJS, I'm receiving like a lot of call and I have to act as a middleware to slow down the number of time I'm calling my function that cause re-render. I need to substract added with newly removed and removed with newly added which I think SelectionJS is already doing some calculation to do this. So I'm undoing what is calculated before. 

**Additional context**

Here a gif of the table being slow down by selection because React-Table need to re-render before even finishing rendering the selection.
![SelectionThrottleNeeded](https://user-images.githubusercontent.com/4070713/110707297-1a05e100-81c7-11eb-9b3e-9a8ada90dcfe.gif)

I think it's funny that my complain/feature request here is about SelectionJS is too fast so other lib aren't able to render selection before they need to re-render and that cause webpage to freeze, so I'm asking a "fps cap" on the onMove function.

**Comment by getreworked** [comment]
@maxime4000 I'm not the creator or a maintainer, but what I would probably do is only commit the update to React-Table on the select `stop` event. This way visually you get the results you need, but you don't cause React to re-render unnecessarily. 

I can't say for sure, but I would expect throttling the onMove event would cause more than a few issues.

**Comment by maxime4000** [comment]
My thought would be to set a throttling to [those 2 lines](https://github.com/Simonwep/selection/blob/0a9fd4084f8e4e1dc1068aa05aed6651dbdafd95/src/index.ts#L383#L384), so when you are going to recalculate the selection, you don't do it yet and wait for the lapse time to pass before recalculate the selection and emitting a new onMove event. That way, you still draw the rect, you still call the onMove function, just not as often as without the throttling.

For sure there is multiple way to get that working. The solution you propose is less "interactive" as the stop would change the selection, but only when you release the selection, but we are searching more like a file explorer selection. For sure, React-Table doesn't offer multiple selection at once so it's a loop of setSelection(rowId, value) which trigger re-render each loop in added, selected, removed and that's why when I'm selecting fast, re-render does not happen, so that could be improve, but I think as a selection lib, having the feature to throttle onMove function might be worth to have. 

In this context, I think React-table could be improve to have a better way to set selection which would improve the re-render, but because SelectionJS is independent of where you use it, adding a throttling feature would allow better control on performance for the users.

Possible issues could being :  that if a onMove is throttling but onStop happen, onStop should force onMove to happen before onStop event is emitted.

**Comment by Simonwep** [comment]
@maxime4000  Thank you for this very elaborated feature request :)  Would it be possible for you to re-create the issue in a [codesandbox](https://codesandbox.io/) (or anything similar)? I'd like to take a closer look at it, maybe there's a way to optimize it without changing anything. It's hard for me to believe that you're already running into performance issues ^^

@getreworked That'd be an solution, yes - but especially with data-driven frameworks I can understand that you _really_ don't want do change (checking the checkboxes) the DOM manually :/ Throtteling the event _could_ cause a few problems, but I'd have to look into it hence I would love to try this out first in a reproduction :)

**Comment by maxime4000** [comment]
@Simonwep So I had it working. So using the kitchen sink example of React-Table, I could replicate that. Here is the [Code Sandbox](https://codesandbox.io/s/twilight-brook-skeui?file=/src/App.js). 
For sure, it's not SelectionJS that is slow, but React-Table, but because SelectionJS onMove can be call multiple times in a very short timespan, React-Table is just not able to update his state before needing to update it's state again. So the goal would be to limit the number of onMove call that can be sent in a short timespan.

**Comment by Simonwep** [comment]
Okay, this is quite a lot what you're doing there - I'd first try using chromes [performance tools](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/) to see what's actually the bottleneck in our case.

I doubt that how often `onMove` is called is the problem, you can easily see this by selecting like 3 rows and just moving around your mouse without selecting more or less - events get fired nonetheless. It only gets slow when your selecting / unselecting elements - not when you're moving your mouse around (which _is_ fireing the `move` event). So I'd probably also look for way to minimize the amount of components which need to be re-rendered.

For example `forEach` is by far the slowest way to iterate an array (followed by `for of` and `for i` being the fastest). Unfortunately I'm not familiar with react-table, but this is where I'd start - the rest can be easily found out using chromes performance tools :)

**Comment by getreworked** [comment]
@Simonwep 

>That'd be an solution, yes - but especially with data-driven frameworks I can understand that you really don't want do change (checking the checkboxes) the DOM manually

Definitely not. I was suggesting that you fake it until the `stop` event. In React it's called an [uncontrolled component](https://reactjs.org/docs/uncontrolled-components.html). By using this approach you eliminate the over rendering caused by constantly updating Reacts state - which is exactly what's happening here. Sure you can try to debounce/throttle the method as OP wants, but you'll just end up with a choppy experience. The solution to his problem, IMO, is to make it look like the rows are selected by applying a class `onMove` and only actually update Reacts state `onStop`.

If you've ever used react-spring and react-use-gesture this is exactly the approach they take so that thery maintain buttery smooth animations. If they updated the state on move their library would be useless.

As an aside regarding performance, you may want to look into how many events are being added when selecting. I've noticed in Chromes performance monitor that the event listeners start climbing rapidly. I haven't noticed a performance hit in my use cases, but it is a bit worrisome.

**Comment by Simonwep** [comment]
I've created a [minimal demo](https://codesandbox.io/s/cool-satoshi-2b6j4?file=/src/index.js) for using selectionjs with (p)react. And there is almost zero performance overhead, yes there are less elements to select but I'm pretty sure that most of your problems are caused by the immense size of your demo / example and things getting re-rendered entirely. In my example It's also not perfect - I'm not even using things like `added` or `removed` to only update only changed elements and it's still super smooth :D

**Comment by maxime4000** [comment]
There is multiple way to get this working without over rendering, but I'm interested in getting the smoothest experience possible without changing dom myself or bypassing some feature of React-table. I want to avoid making a middleware feature to slowdown the onMove function so I can get smoother experience when moving the mouse. 

The table is the main part of the site so it need to be responsive and it's the heavy part of the app so creating a minimal example doesn't represent my actual needs. I know I'm doing a lot here and that's why I'm saying SelectionJS is not the issues here. 
The issues here is : SelectionJS can send like 10-20 onMove call in like seconds and because I'm just passing onMove function from SelectionJS to React-Table directly, React-Table is over rendering his selection and it's an heavy process and it cannot re-render that fast. So limiting the number of time SetSelection is called per second would allow React-Table to render once or twice per seconds instead of 10 to 20 times. 

I'm trying to connect 2 features of 2 different libraries and making them work together like if it was one feature and I'm trying to avoid making a complex connector to get the smoothest experience I can get. If I take the docs example, you only add/remove class on the elements you are selecting which is very fast, but that would mean bypassing React-Table selection feature and it's not what I'm looking for. 

I'm asking the feature because I think a throttling feature would make sense in SelectionJS. It doesn't add much if not use, but if use, it help maintaining smooth rendering when each change in selection is triggering heavy computation that can freeze the UI. 

That being said, I'm suggesting/requesting this feature here, because it is not my focus right now to make our selection smoother. I was planning to do it in the future. If adding a Throttle feature is fine by the owner, I can take care of pushing a Pull Request on a later date, but if SelectionJS does not want the throttle feature, I will throttle the connector and never talk about it again. I just think it's more efficient and useful to add the throttle in SelectionJS than in our connector.

**Comment by Simonwep** [comment]
Alright, I get your point. The problem I have that many issues, such as this, can be easily "fixed" by using a "debounce" function as middleware between the event-handler and your function. For example:

```ts
selection.on('move', debounce(evt => {
    // ...
}, 50)); // Debouncing the function call at a rate of 50ms
```
Such a `debounce` function is pretty basic, I could even export such a function from an `utils` module in selectionjs. The reason why I don't want to add this to selectionjs is because it's not directly related to the code functionality, it's an modification, an extension of the outcome of a functionality - not part of it. Even if 50% of the developers using it uses it, the rest is still having this piece of "unrelated" code as part of the bundle which adds up in size and increases complexity (not much - yes, but this sums up if you keep adding "nice to haves", see [pickr](https://github.com/Simonwep/pickr) - the reason I deprecated it is exactly this).

Why would you prefer my solution over selection-js offering it out of the box? Instead of having a `throttle: 5` property _somewhere_ you can have this little piece of code right where it belongs, and if somebody visits this it'll immediately be like "Ah - this function is throttled". Also: Since this _is_  a basic function you can reuse the `debounce` at any other part of your app, reducing duplicate code. And the performance? Better, because debounce returns a function and selectionjs is still doing the maximum to preserve high core-performance - no if-checks or what-else to implement a custom `debounce` function.

> I'm asking the feature because I think a throttling feature would make sense in SelectionJS. It doesn't add much if not use, but if use.

The "It doesn't add much if not use, but if use" part is already telling you two things:
* This isn't relevant for everybody (Smaller bundle-size and improved readability)
* This is a small feature (There is most likely a public tool to do this at a much higher efficiency)

So, given the points above I say you should make use of a well-tested, published [`debounce` utility](https://www.npmjs.com/package/debounce) such as  since, adding my own doesn't add any value since I'd be copying the code from it and wouldn't actively maintain this function (and it might behave different depending on how the debounce-package changes - inconsistency).

I'm not exactly familiar with the Adaptar design pattern, but what I try is to make it as easy to understand for those who will see this library in use by others, the ones who'll used it and maintain modularity and performance as good a possible. And using a `debounce` function as "middle-man" or your Adapter I think is the best solution here. The only thing that's lost is ease-of-use, but even that is not given given the fact that others, as I mentioned, would have to first read the docs or look up the selection-area initialization to find out what this "throtteling" is caused by.

I appreciate your feature-request and the elaborated comments, if there are any more questions or Ideas or maybe I'm completely off and just don't get it (most likely) - please correct me. I just want it to be better than the ones before :)

**Comment by maxime4000** [comment]
I did have try debounce. The reason it ain't work is the Removed array is is lost when you debounce multiple time. 
If I select 10 element, I move my mouse to the fifth element. It should be staying 5 elements instead of 10. Right ? 
Wrong ! 
Debounce will eat the Removed array and you might end up with 9 selected even if you select the fifth. While 6-7-8-9-10 should be removed, only the sixth elements might get removed because he is the last debounce call done. To counter that, you would need to clear the selection every time you call debounce which is like asking more Re-Render from React-Table.
This would affect Added too if the Selected would not compensate that. Reason: After Added is done, Selected own the same Added item. But Selected do not own the Removed item which is why debounce eat Removed element event and they are not removed
## No debounce, this is the log of event :
```.js
onMove({Removed: [10], Added:[], Selected:[1...9]}); // Succeeded
onMove({Removed: [9], Added:[], Selected:[1...8]}); // Succeeded
onMove({Removed: [8], Added:[], Selected:[1...7]}); // Succeeded, Might start getting UI Freeze at this point
onMove({Removed: [7], Added:[], Selected:[1...6]}); // Succeeded, Still work even if UI is freeze
onMove({Removed: [6], Added:[], Selected:[1...5]}); // Succeeded, Still work even if UI is freeze
```
## With debounce, this is the log of event :
```.js
debounce(onMove({Removed: [10], Added:[], Selected:[1...9]})); // Wait X millisecond, Missed by new debounce call
debounce(onMove({Removed: [9], Added:[], Selected:[1...8]})); // Reset, Missed by new debounce call
debounce(onMove({Removed: [8], Added:[], Selected:[1...7]})); // Reset, Missed by new debounce call
debounce(onMove({Removed: [7], Added:[], Selected:[1...6]})); // Reset, Missed by new debounce call
debounce(onMove({Removed: [6], Added:[], Selected:[1...5]})); // Wait X millisecond and Function is called (Succeeded)
```
Which result in this selection outside of SelectionJS : [1, 2, 3, 4, 5, 7, 8, 9, 10] // 6 was removed

**Note : Debounce is affected by UI Freeze so if you debounce(()=> {}, 10); but UI Freeze for 100 milliseconds, your debounce might be override even if it should have been sent 90 millisecond earlier.** 
# With debounce not working how do you make that work ? 
[Well that where I think those 2 lines would be needed to be throttle.](https://github.com/Simonwep/selection/blob/0a9fd4084f8e4e1dc1068aa05aed6651dbdafd95/src/index.ts#L383#L384) With throttling here, you calculate the { Selected, Added, Removed } when the throttle decide it's time to calculate and send a onMove event with the new calculated event. 
## Doing the same with Throttle from my suggestion in SelectionJS :
```
// First event of Throttle is call
throttle(onMove({Removed: [10], Added:[], Selected:[1...9]})); // Sent
// 3 onMove Event miss before Throttle is sent
throttle(onMove({Removed: [9, 8, 7], Added:[], Selected:[1...6]})); // Sent
// 1 onMove Event miss before Throttle is sent
throttle(onMove({Removed: [6], Added:[], Selected:[1...5]})); // Sent
```
End Result is [1, 2, 3, 4, 5] 
Here's how it change : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] => [1, 2, 3, 4, 5, 6, 7, 8, 9] => [1, 2, 3, 4, 5, 6] => [1, 2, 3, 4, 5]

## For throttling in SelectionJS
So you are right that if people do not know about throttling they will have to look at it, but what I'm suggesting throttling is disable by default. I would set this as an optional property. Simple condition like this : 
```.js
// Concept, not real code
if(this._options.throttleArgs){
  throttle(() => {
    this._updateElementSelection();
    this._emitEvent('move', evt);
  }, this._options.throttleArgs);
} else {
  this._updateElementSelection();
  this._emitEvent('move', evt);
}
```
For the package size part, my idea would be that dev are expected to bring their own throttling function as argument instead of having a dependency for throttling, but I have no idea if that's realistic. Personally, package size is the least of my concern, but we can find a workaround if that's important.

**Comment by Simonwep** [comment]
Okay, I didn't see that, sorry - this is getting a bit more complex as I thought it'd be. What about introducing a "change" function which only fires if the selection has changed? I'll take a look at it on the next weekend either way, this should get "fixed" in any way at the end of the week :)

**Comment by maxime4000** [comment]
Well the onMove function is trigger every time a new item or removed item event happen so unless I'm misunderstanding what you are suggesting, it's kinda what's is already in place. 
**Note :** I think trigger event also happen when there is no changes, but I might be wrong on that, I just know that debounce sometime didn't remove the sixth elements, but I never investigate why, I just know that this solution was flawed so I had to think about an other way to merge multiple SelectionEvent into one that is call less often which is why I though about throttle and SelectionJS having this feature.

My though is that throttling selection calculation will concat multiple X Removed/Added event into one bigger onMove call instead of being X number of individual Added or Removed event sent in the same timespan. 

Thanks for reconsidering my issues, I didn't know how to explain it first because of the complexity it involve.
Anyway, I'm looking forward to test your fixed :)

**Comment by Simonwep** [comment]
> Well the onMove function is trigger every time a new item or removed item event happen so unless I'm misunderstanding what you are suggesting, it's kinda what's is already in place.

`move` is fired when you're moving the mouse around, that doesn't necessarily mean that the selection has changed.

> My though is that throttling selection calculation will concat multiple X Removed/Added event into one bigger onMove call instead of being X number of individual Added or Removed event sent in the same timespan.

I think that the whole "fire only when the selection **changed**" will fix it, as stated above this is currently only bound to the mouse _movements_...

**Comment by Simonwep** [comment]
Okay, I worked out a small demo for you @maxime4000 - this is what I had in mind, could you apply that to your example / code and see if there are any improvements? I also added a counter in my example to show the difference between _changes_ and _moves_, the importand bit for you can be found in the `move` IIEF function: https://jsfiddle.net/Simonwep/4p3roadL/

**Comment by Simonwep** [comment]
Since many of you requested this feature I'll take another look at it next month... I see the reason for this in case of a very large amount of elements - it should be possible for this library to handle this, even if it means that something has to be throttled.

**Comment by amz931128** [comment]
> 我确实尝试过去抖动。它不起作用的原因是当您多次去抖动时，删除数组丢失了。 如果我选择10个元素，我将鼠标移动到第五个元素。它应该保留5个元素而不是 10 个。对吗？ 错误的！ Debounce 会吃掉 删除了数组，即使您选择了第 5 个，您最终也可能会选择 9 个。虽然 6-7-8-9-10 应该被删除，但只有第一个元素可能会被删除，因为他是最后一个完成的去快速调用。为了解决问题，每次调用去抖动时都需要清除选择，这就像从 React-Table 要求更多的 Re-Render。 如果选择不补偿，这也会影响添加。原因：添加完成后，拥有选择的相同项目添加但是选择不拥有删除项目，这就是为什么抖吃移除的元素事件并且它们没有被删除
> 
> ## 没有去狂欢，这是事件的：
> ```js
> onMove （{删除：[ 10 ] ， 加：[ ] ， 选定的：[ 1 。0.9 ] } ）;  // 成功
> onMove ( { Removed : [ 9 ] , 添加: [ ] ,  Selected : [ 1. . .8 ] } ) ;  // 成功
> onMove ( {移除:[ 8 ] ， 添加：[ ] ， 选择：[ 1 .. .7 ] } ) ;  // 成功，此时可能会开始让 UI
> 融合 onMove ( { Removed : [ 7 ] , 添加: [ ] ,  Selected : [ 1. . .6 ] } ) ;  // 成功，即使 UI 冻结
> on Move仍然有效（{ 已删除：[ 6] ， 添加：[ ] ， 选择：[ 1 .. .5 ] } ) ;  // 成功，即使 UI 冰冻仍然有效
> ```
> 
> ## 使用 debounce，这是事件的日志：
> ```js
> 去抖动（onMove （{删除：[ 10 ] ， 加：[ ] ， 选定的：[ 1 。0.9 ] } ））;  //等待X毫秒，新由去的抖呼叫未接
> 反跳（onMove （{删除：[ 9 ] ， 添加了：[ ] ， 选定的：[ 1 。0.8 ] } ））; //复位，新由去的抖呼叫未接
> 反跳（onMove （{删除：[ 8 ] ， 添加了：[ ] ， 选定的：[ 1 。0.7 ] } ））;  //复位，由新的去抖呼叫未接
> 反跳（onMove （{删除：[ 7 ] ， 添加了：[ ] ， 选定的：[ 1 。. .6 ] } ) );  //复位，新由去的抖呼叫未接
> 反跳（onMove （{删除：[ 6 ] ， 添加了：[ ] ， 选定的：[ 1 。0.5 ] } ））;  //等待X毫秒并调用函数（成功）
> ```
> 
> 这导致了 SelectionJS 之外的这个选择：[1, 2, 3, 4, 5, 7, 8, 9, 10] // 6 被删除
> 
> **注意：Debounce 会受 UI Freeze 的影响，如果你 debounce(()=> {}, 10);但是 UI 融化了 100 毫秒，您的去鲨鱼可能会被覆盖，即使它应该提前 90 毫秒发送。**
> 
> # 如果不反弹，你怎么容易出手？
> [好，我认为这 2 行需要节流阀。](https://github.com/Simonwep/selection/blob/0a9fd4084f8e4e1dc1068aa05aed6651dbdafd95/src/index.ts#L383#L384)通过这里的节流，您可以在节流阀决定计算并发送新计算事件的 onMove 事件时计算 { Selected, Added, Removed }。
> 
> ## 可知我在SelectionJS 中的建议对Throttle 做同样的事情：
> ```
> // First event of Throttle is call
> throttle(onMove({Removed: [10], Added:[], Selected:[1...9]})); // Sent
> // 3 onMove Event miss before Throttle is sent
> throttle(onMove({Removed: [9, 8, 7], Added:[], Selected:[1...6]})); // Sent
> // 1 onMove Event miss before Throttle is sent
> throttle(onMove({Removed: [6], Added:[], Selected:[1...5]})); // Sent
> ```
> 
> 最终结果是 [1, 2, 3, 4, 5] 其变化如下： [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] => [1, 2, 3, 4 , 5, 6, 7, 8, 9] => [1, 2, 3, 4, 5, 6] => [1, 2, 3, 4, 5]
> 
> ## 用于在 SelectionJS 中进行节流
> 所以你是对的，如果人们不知道自己选择节，他们将不得不采用它，但我希望节是自愿的属性。我看其流这样设置为。像的简单条件：
> 
> ```js
> //概念，而不是真正的代码
> ，如果（此。_options 。throttleArgs ）{
>   节气门（（） =>  {
>     此。_updateElementSelection （）;
>     此。_emitEvent （'移动' ， EVT ）; 
>   } ， 此。_options 。throttleArgs ）; 
> } 其他 {
>   这个。_updateElementSelection （）;
>   这个。_emitEvent ( '移动' ,  evt ) ; 
> }
> ```
> 
> 对于包大小，我的想法是开发人员应该将他们自己的节流作为参数而不是依赖于节流，但我不知道这是否现实。就我个人而言，包大小是我最不关心的，但如果这很重要，我们可以找到解决方法。



> I did have try debounce. The reason it ain't work is the Removed array is is lost when you debounce multiple time. If I select 10 element, I move my mouse to the fifth element. It should be staying 5 elements instead of 10. Right ? Wrong ! Debounce will eat the Removed array and you might end up with 9 selected even if you select the fifth. While 6-7-8-9-10 should be removed, only the sixth elements might get removed because he is the last debounce call done. To counter that, you would need to clear the selection every time you call debounce which is like asking more Re-Render from React-Table. This would affect Added too if the Selected would not compensate that. Reason: After Added is done, Selected own the same Added item. But Selected do not own the Removed item which is why debounce eat Removed element event and they are not removed
> 
> ## No debounce, this is the log of event :
> ```js
> onMove({Removed: [10], Added:[], Selected:[1...9]}); // Succeeded
> onMove({Removed: [9], Added:[], Selected:[1...8]}); // Succeeded
> onMove({Removed: [8], Added:[], Selected:[1...7]}); // Succeeded, Might start getting UI Freeze at this point
> onMove({Removed: [7], Added:[], Selected:[1...6]}); // Succeeded, Still work even if UI is freeze
> onMove({Removed: [6], Added:[], Selected:[1...5]}); // Succeeded, Still work even if UI is freeze
> ```
> 
> ## With debounce, this is the log of event :
> ```js
> debounce(onMove({Removed: [10], Added:[], Selected:[1...9]})); // Wait X millisecond, Missed by new debounce call
> debounce(onMove({Removed: [9], Added:[], Selected:[1...8]})); // Reset, Missed by new debounce call
> debounce(onMove({Removed: [8], Added:[], Selected:[1...7]})); // Reset, Missed by new debounce call
> debounce(onMove({Removed: [7], Added:[], Selected:[1...6]})); // Reset, Missed by new debounce call
> debounce(onMove({Removed: [6], Added:[], Selected:[1...5]})); // Wait X millisecond and Function is called (Succeeded)
> ```
> 
> Which result in this selection outside of SelectionJS : [1, 2, 3, 4, 5, 7, 8, 9, 10] // 6 was removed
> 
> **Note : Debounce is affected by UI Freeze so if you debounce(()=> {}, 10); but UI Freeze for 100 milliseconds, your debounce might be override even if it should have been sent 90 millisecond earlier.**
> 
> # With debounce not working how do you make that work ?
> [Well that where I think those 2 lines would be needed to be throttle.](https://github.com/Simonwep/selection/blob/0a9fd4084f8e4e1dc1068aa05aed6651dbdafd95/src/index.ts#L383#L384) With throttling here, you calculate the { Selected, Added, Removed } when the throttle decide it's time to calculate and send a onMove event with the new calculated event.
> 
> ## Doing the same with Throttle from my suggestion in SelectionJS :
> ```
> // First event of Throttle is call
> throttle(onMove({Removed: [10], Added:[], Selected:[1...9]})); // Sent
> // 3 onMove Event miss before Throttle is sent
> throttle(onMove({Removed: [9, 8, 7], Added:[], Selected:[1...6]})); // Sent
> // 1 onMove Event miss before Throttle is sent
> throttle(onMove({Removed: [6], Added:[], Selected:[1...5]})); // Sent
> ```
> 
> End Result is [1, 2, 3, 4, 5] Here's how it change : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] => [1, 2, 3, 4, 5, 6, 7, 8, 9] => [1, 2, 3, 4, 5, 6] => [1, 2, 3, 4, 5]
> 
> ## For throttling in SelectionJS
> So you are right that if people do not know about throttling they will have to look at it, but what I'm suggesting throttling is disable by default. I would set this as an optional property. Simple condition like this :
> 
> ```js
> // Concept, not real code
> if(this._options.throttleArgs){
>   throttle(() => {
>     this._updateElementSelection();
>     this._emitEvent('move', evt);
>   }, this._options.throttleArgs);
> } else {
>   this._updateElementSelection();
>   this._emitEvent('move', evt);
> }
> ```
> 
> For the package size part, my idea would be that dev are expected to bring their own throttling function as argument instead of having a dependency for throttling, but I have no idea if that's realistic. Personally, package size is the least of my concern, but we can find a workaround if that's important.

**Comment by amz931128** [comment]
> I did have try debounce. The reason it ain't work is the Removed array is is lost when you debounce multiple time. If I select 10 element, I move my mouse to the fifth element. It should be staying 5 elements instead of 10. Right ? Wrong ! Debounce will eat the Removed array and you might end up with 9 selected even if you select the fifth. While 6-7-8-9-10 should be removed, only the sixth elements might get removed because he is the last debounce call done. To counter that, you would need to clear the selection every time you call debounce which is like asking more Re-Render from React-Table. This would affect Added too if the Selected would not compensate that. Reason: After Added is done, Selected own the same Added item. But Selected do not own the Removed item which is why debounce eat Removed element event and they are not removed
> 
> ## No debounce, this is the log of event :
> ```js
> onMove({Removed: [10], Added:[], Selected:[1...9]}); // Succeeded
> onMove({Removed: [9], Added:[], Selected:[1...8]}); // Succeeded
> onMove({Removed: [8], Added:[], Selected:[1...7]}); // Succeeded, Might start getting UI Freeze at this point
> onMove({Removed: [7], Added:[], Selected:[1...6]}); // Succeeded, Still work even if UI is freeze
> onMove({Removed: [6], Added:[], Selected:[1...5]}); // Succeeded, Still work even if UI is freeze
> ```
> 
> ## With debounce, this is the log of event :
> ```js
> debounce(onMove({Removed: [10], Added:[], Selected:[1...9]})); // Wait X millisecond, Missed by new debounce call
> debounce(onMove({Removed: [9], Added:[], Selected:[1...8]})); // Reset, Missed by new debounce call
> debounce(onMove({Removed: [8], Added:[], Selected:[1...7]})); // Reset, Missed by new debounce call
> debounce(onMove({Removed: [7], Added:[], Selected:[1...6]})); // Reset, Missed by new debounce call
> debounce(onMove({Removed: [6], Added:[], Selected:[1...5]})); // Wait X millisecond and Function is called (Succeeded)
> ```
> 
> Which result in this selection outside of SelectionJS : [1, 2, 3, 4, 5, 7, 8, 9, 10] // 6 was removed
> 
> **Note : Debounce is affected by UI Freeze so if you debounce(()=> {}, 10); but UI Freeze for 100 milliseconds, your debounce might be override even if it should have been sent 90 millisecond earlier.**
> 
> # With debounce not working how do you make that work ?
> [Well that where I think those 2 lines would be needed to be throttle.](https://github.com/Simonwep/selection/blob/0a9fd4084f8e4e1dc1068aa05aed6651dbdafd95/src/index.ts#L383#L384) With throttling here, you calculate the { Selected, Added, Removed } when the throttle decide it's time to calculate and send a onMove event with the new calculated event.
> 
> ## Doing the same with Throttle from my suggestion in SelectionJS :
> ```
> // First event of Throttle is call
> throttle(onMove({Removed: [10], Added:[], Selected:[1...9]})); // Sent
> // 3 onMove Event miss before Throttle is sent
> throttle(onMove({Removed: [9, 8, 7], Added:[], Selected:[1...6]})); // Sent
> // 1 onMove Event miss before Throttle is sent
> throttle(onMove({Removed: [6], Added:[], Selected:[1...5]})); // Sent
> ```
> 
> End Result is [1, 2, 3, 4, 5] Here's how it change : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] => [1, 2, 3, 4, 5, 6, 7, 8, 9] => [1, 2, 3, 4, 5, 6] => [1, 2, 3, 4, 5]
> 
> ## For throttling in SelectionJS
> So you are right that if people do not know about throttling they will have to look at it, but what I'm suggesting throttling is disable by default. I would set this as an optional property. Simple condition like this :
> 
> ```js
> // Concept, not real code
> if(this._options.throttleArgs){
>   throttle(() => {
>     this._updateElementSelection();
>     this._emitEvent('move', evt);
>   }, this._options.throttleArgs);
> } else {
>   this._updateElementSelection();
>   this._emitEvent('move', evt);
> }
> ```
> 
> For the package size part, my idea would be that dev are expected to bring their own throttling function as argument instead of having a dependency for throttling, but I have no idea if that's realistic. Personally, package size is the least of my concern, but we can find a workaround if that's important.


Has this problem been solved？

**Comment by Simonwep** [comment]
Instead of adding a throttle option I tried optimizing it by aligning each frame with the current framerate making it technically as "fast as possible", please try out 3.0.0-beta.12 :)
